# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("psych", "ggplot2"))
library(psych)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)

# === 01 · Exploratory factor analysis (EFA) ===
items <- c("x1", "x2", "x3", "x4", "x5", "x6", "x7", "x8", "x9")
d_items <- d[, items, drop = FALSE]
n <- nrow(d_items)

# ---- EFA: suitability ----
library(psych)
R_cor <- cor(d_items)
kmo_val <- psych::KMO(R_cor)$MSA
cat("KMO:", round(kmo_val, 3), "\n")
bart_obj <- psych::cortest.bartlett(R_cor, n = n)
cat("Bartlett chisq:", round(bart_obj$chisq, 1), "df:", bart_obj$df, "p:", bart_obj$p.value, "\n")

# ---- Parallel analysis for retention ----
x <- as.matrix(d_items); nsim <- 500L; seed <- 20260619L; kind <- "fa"
set.seed(seed)
n_pa <- nrow(x); p_pa <- ncol(x)
R_pa <- cor(x); smc_v <- psych::smc(R_pa); smc_v <- pmin(pmax(smc_v, 0), 1); diag(R_pa) <- smc_v
obs_eig <- sort(eigen(R_pa, symmetric = TRUE, only.values = TRUE)$values, decreasing = TRUE)
sim_e <- matrix(0, nsim, p_pa)
for (i in seq_len(nsim)) {
  rx <- matrix(rnorm(n_pa * p_pa), n_pa, p_pa)
  Rs <- cor(rx); sv <- psych::smc(Rs); sv <- pmin(pmax(sv, 0), 1); diag(Rs) <- sv
  sim_e[i, ] <- sort(eigen(Rs, symmetric = TRUE, only.values = TRUE)$values, decreasing = TRUE)
}
sim_p95 <- apply(sim_e, 2, quantile, probs = 0.95)
k_retain <- 0L
for (i in seq_len(p_pa)) { if (obs_eig[i] > sim_p95[i]) k_retain <- k_retain + 1L else break }
cat("Parallel analysis retain:", k_retain, "\n")

# ---- psych::fa ----
fm_method <- "pa"
fa_obj <- psych::fa(d_items, nfactors = k_retain, fm = fm_method, rotate = "oblimin")
cat("\n--- Table 2: Variance explained ---\n")
print(round(fa_obj$Vaccounted, 3))
cat("\n--- Table 3: Rotated loadings + communalities ---\n")
load_mat <- unclass(fa_obj$loadings)
h2 <- fa_obj$communality
out_mat <- cbind(load_mat, communality = h2)
print(round(out_mat, 3))

# ---- Phi: interfactor correlations (oblique) ----
if (!is.null(fa_obj$Phi)) {
  cat("\n--- Table 4: Interfactor correlations (Phi) ---\n")
  print(round(fa_obj$Phi, 3))
}