# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("modelsummary", "ggplot2", "performance", "pROC"))
library(modelsummary)
library(ggplot2)
library(performance)
library(pROC)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$passed <- factor(d$passed)
d$group <- factor(d$group)

# === 01 · Logistic regression ===
# re-level the outcome so the chosen event becomes glm's SECOND factor level
oth <- setdiff(sort(unique(as.character(d$passed))), "yes")
d$passed <- factor(as.character(d$passed), levels = c(oth, "yes"))
m <- glm(passed ~ pre_score + age + group, family = binomial, data = d)
modelsummary(list("Odds ratio" = m), exponentiate = TRUE, statistic = "conf.int", stars = FALSE, fmt = 3, gof_map = c("nobs", "r.squared", "adj.r.squared", "aic", "bic", "logLik", "rmse"), output = "markdown")
# omnibus chi-square + pseudo-R2 (report-only footer stats)
# single overall likelihood-ratio omnibus: null - residual deviance (mirrors logisticRegression.ts)
omnibus <- m$null.deviance - m$deviance
omnibus_df <- m$df.null - m$df.residual
omnibus_p <- pchisq(omnibus, omnibus_df, lower.tail = FALSE)
print(c(omnibus_chisq = omnibus, df = omnibus_df, p = omnibus_p))
print(performance::r2_nagelkerke(m))
# Classification table — cutoff P(event) >= 0.5, rows = predicted level
p <- fitted(m)
pred <- factor(ifelse(p >= 0.5, "yes", oth[1]), levels = levels(d$passed))
print(table(pred, d$passed))
# ROC curve + AUC
roc_obj <- pROC::roc(d$passed, p, quiet = TRUE)
auc_val <- as.numeric(pROC::auc(roc_obj))
print(ggplot(data.frame(fpr = 1 - roc_obj$specificities, tpr = roc_obj$sensitivities), aes(fpr, tpr)) +
  geom_abline(slope = 1, intercept = 0, colour = "#9cc2ec", linetype = "dashed") +
  geom_line(colour = "#0c447c", linewidth = 0.8) +
  annotate("text", x = 0.7, y = 0.15, label = sprintf("AUC = %.3f", auc_val)) +
  coord_equal() + labs(x = "1 - Specificity", y = "Sensitivity"))