# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("modelsummary", "ggplot2", "performance", "pROC"))
library(modelsummary)
library(ggplot2)
library(performance)
library(pROC)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d[["passed_course"]] <- factor(d[["passed_course"]])
d[["teaching_method"]] <- factor(d[["teaching_method"]])

# === 01 · Logistic regression ===
# re-level the outcome so the chosen event becomes glm's SECOND factor level
oth <- setdiff(sort(unique(as.character(d$passed_course))), "Yes")
d$passed_course <- factor(as.character(d$passed_course), levels = c(oth, "Yes"))
m <- glm(passed_course ~ pretest_score + study_hours_per_week + teaching_method, family = binomial, data = d)
modelsummary(list("Odds ratio" = m), exponentiate = TRUE, statistic = "conf.int", stars = FALSE, fmt = 3, gof_map = c("nobs", "r.squared", "adj.r.squared", "aic", "bic", "logLik", "rmse"), output = "markdown")
# omnibus chi-square + pseudo-R2 (report-only footer stats)
# single overall likelihood-ratio omnibus: null - residual deviance (mirrors logisticRegression.ts)
omnibus <- m$null.deviance - m$deviance
omnibus_df <- m$df.null - m$df.residual
omnibus_p <- pchisq(omnibus, omnibus_df, lower.tail = FALSE)
print(c(omnibus_chisq = omnibus, df = omnibus_df, p = omnibus_p))
print(performance::r2_nagelkerke(m))
# Classification table — cutoff P(event) >= 0.5, rows = predicted level
p <- fitted(m)
pred <- factor(ifelse(p >= 0.5, "Yes", oth[1]), levels = levels(d$passed_course))
tab <- table(pred, d$passed_course)
print(tab)
# Accuracy/sensitivity/specificity (R1 gap-fix, worked example)
cat("Accuracy:", sum(diag(tab)) / sum(tab), "\n")
cat("Sensitivity:", tab["Yes", "Yes"] / sum(tab[, "Yes"]), "\n")
cat("Specificity:", tab[oth[1], oth[1]] / sum(tab[, oth[1]]), "\n")
# ROC curve + AUC (+ 95% CI, R1 gap-fix — pROC::ci.auc, DeLong method, deterministic)
roc_obj <- pROC::roc(d$passed_course, p, quiet = TRUE)
auc_val <- as.numeric(pROC::auc(roc_obj))
print(pROC::ci.auc(roc_obj))
print(ggplot(data.frame(fpr = 1 - roc_obj$specificities, tpr = roc_obj$sensitivities), aes(fpr, tpr)) +
  geom_abline(slope = 1, intercept = 0, colour = "#9cc2ec", linetype = "dashed") +
  geom_line(colour = "#0c447c", linewidth = 0.8) +
  annotate("text", x = 0.7, y = 0.15, label = sprintf("AUC = %.3f", auc_val)) +
  coord_equal() + labs(x = "1 - Specificity", y = "Sensitivity"))