# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("ggplot2"))
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)

# === 01 · Pearson correlation ===
ct <- cor.test(d[["hours_studied"]], d[["exam_score"]], method = "pearson", conf.level = 0.95, alternative = "two.sided")
print(ct)
print(ggplot(d, aes(hours_studied, exam_score)) + geom_point() + geom_smooth(method = "lm"))