# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("coin", "effectsize", "ggplot2"))
library(coin)
library(effectsize)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)

# === 01 · Wilcoxon signed-rank ===
a <- d[["pre"]]; b <- d[["post"]]
res <- wilcox.test(a, b, paired = TRUE, correct = TRUE, alternative = "two.sided")
print(res)
print(coin::wilcoxsign_test(a ~ b))
print(effectsize::rank_biserial(a, b, paired = TRUE))
print(ggplot(data.frame(case = factor(seq_along(a)), d = a - b), aes(case, d)) +
  geom_col(fill = "#9cc2ec", colour = "#0c447c") + geom_hline(yintercept = 0, colour = "#0c447c") +
  labs(x = "Case", y = "Difference (A - B)"))