# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("emmeans", "ggplot2"))
library(emmeans)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$group <- factor(d$group)

# === 01 · MANCOVA ===
# covariates FIRST, factor(s) LAST -> factor row matches car::Manova Type II (spike-proven)
m <- manova(cbind(d[["outcome"]], d[["outcome2"]]) ~ d[["baseline"]] + factor(d[["group"]]))
print(summary(m, test = "Pillai"))
print(summary(aov(d[["outcome"]] ~ d[["baseline"]] + factor(d[["group"]]))))
print(summary(aov(d[["outcome2"]] ~ d[["baseline"]] + factor(d[["group"]]))))
agg <- do.call(rbind, lapply(list(c(d[["outcome"]]), c(d[["outcome2"]])), function(v) {
  d2 <- data.frame(y = v, cov_1 = d[["baseline"]], fac_1 = factor(d[["group"]]))
  lm_fit <- lm(y ~ cov_1 + fac_1, data = d2)
  em <- as.data.frame(emmeans::emmeans(lm_fit, ~ fac_1))
  data.frame(g = as.character(em[["fac_1"]]), m = em$emmean, lo = em$lower.CL, hi = em$upper.CL) }))
agg$dv <- rep(c("outcome", "outcome2"), each = nlevels(factor(d[["group"]])))
print(ggplot(agg, aes(g, m)) + geom_pointrange(aes(ymin = lo, ymax = hi), colour = "#0c447c") +
  facet_wrap(~dv, scales = "free_y") + labs(x = NULL, y = NULL))