import { describe, it, expect } from 'vitest'
import { emitRScript } from './emit'
import { SPECS } from '../../registry/catalog'
import type { Dataset } from '../../stats/types'

const dataset: Dataset = {
  columns: ['post_score', 'pre_score'],
  rows: [{ post_score: 80, pre_score: 70 }, { post_score: 90, pre_score: 85 }, { post_score: 75, pre_score: 60 }],
}
const setup = { roles: { outcome: ['post_score'], predictor: ['pre_score'] }, options: {}, props: {}, blocked: null }

describe('emitRScript — backbone + simple-linear reference emitter', () => {
  const script = emitRScript(['simple-linear-regression'], { 'simple-linear-regression': setup }, SPECS, dataset)

  it('opens with the Telos header banner', () => {
    expect(script.startsWith('# Reproducible analysis script generated by Telos')).toBe(true)
  })
  it('emits a commented install.packages line + a library() line per package', () => {
    expect(script).toContain('# install.packages(c("modelsummary", "ggplot2"))')
    expect(script).toContain('library(modelsummary)')
    expect(script).toContain('library(ggplot2)')
  })
  it('reads the cleaned dataset', () => {
    expect(script).toContain('read.csv("cleaned.csv"')
  })
  it('opens a numbered, named block per selected test', () => {
    expect(script).toContain('# === 01 · Simple linear regression ===')
  })
  it('mirrors the lm() call with the real role columns', () => {
    expect(script).toContain('lm(post_score ~ pre_score, data = d)')
  })
  it('emits the canonical modelsummary() report-only call', () => {
    expect(script).toContain('modelsummary(')
    expect(script).toContain('stars = FALSE')
  })
})
