import type { Dataset } from '../../stats/types'

// Shared, pure string-returning snippets the per-family emitters compose.
// The format here is pinned by emit.test.ts — keep it stable so Tasks 3-5 stay consistent.

const q = (s: string) => `"${s}"`

/** Leading comment banner + a commented install line (running the script never forces installs) + a library() per package. */
export function header(pkgs: string[]): string {
  const lines = [
    '# Reproducible analysis script generated by Telos',
    '# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.',
  ]
  if (pkgs.length) {
    lines.push(`# install.packages(c(${pkgs.map(q).join(', ')}))`)
    for (const p of pkgs) lines.push(`library(${p})`)
  }
  return lines.join('\n')
}

/** `rename`: raw CSV column -> sanitized R-side token, for callers whose emitted model text references
 *  columns as bare lavaan/seminr identifiers (display names with spaces are illegal there). R's read.csv
 *  DEFAULT check.names=TRUE would mangle a spaced header via make.names() (e.g. a space -> a period),
 *  which does NOT match the app's lvNames-derived token — so a rename target is only reachable with
 *  check.names=FALSE + an explicit rename right after the read, giving byte-for-byte parity with the
 *  in-app WebR runtime's naming. Omitted/empty (every non-SEM family, and any SEM columns that already
 *  sanitize to themselves) keeps this byte-identical to the un-parameterized call. */
export function readData(rename?: [string, string][]): string {
  const base = `d <- read.csv("cleaned.csv", stringsAsFactors = FALSE${rename?.length ? ', check.names = FALSE' : ''})`
  if (!rename || rename.length === 0) return base
  const from = rename.map(([raw]) => JSON.stringify(raw)).join(', ')
  const to = rename.map(([, safe]) => JSON.stringify(safe)).join(', ')
  return `${base}\ncolnames(d)[match(c(${from}), colnames(d))] <- c(${to})`
}

/** All-numeric non-missing values → leave as-is; else factor (mirrors simpleLinearRegression's isNumericColumn classification). */
const isNumericColumn = (data: Dataset, col: string): boolean => {
  const vals = data.rows.map((r) => r[col]).filter((v) => v !== null && v !== undefined && String(v).trim() !== '')
  return vals.length > 0 && vals.every((v) => typeof v === 'number')
}

/** `d[["<col>"]] <- factor(d[["<col>"]])` for each role column that reads as categorical. Best-effort,
 *  one line per column. Bracket accessor (not bare `d$<col>`) so a spaced column name is valid R syntax
 *  here too — byte-behaviorally identical to the old `d$<col>` form for every currently-passing fixture. */
export function factorLines(setup: { roles: Record<string, string[]> }, _spec: unknown, dataset: Dataset): string {
  const cols = [...new Set(Object.values(setup.roles).flat())]
  return cols
    .filter((c) => dataset.columns.includes(c) && !isNumericColumn(dataset, c))
    .map((c) => `d[["${c}"]] <- factor(d[["${c}"]])`)
    .join('\n')
}

/** The canonical report-only modelsummary() call (spike §3): no stars, SE + CI beneath, GOF footer silently dropping rows a family lacks. */
export function modelsummaryCall(modelVar: string, opts: { gof?: string; exponentiate?: boolean } = {}): string {
  const stat = opts.exponentiate ? '"conf.int"' : 'c("std.error", "conf.int")'
  const head = opts.exponentiate ? '"Odds ratio"' : '"(1)"'
  const exp = opts.exponentiate ? 'exponentiate = TRUE, ' : ''
  return `modelsummary(list(${head} = ${modelVar}), ${exp}statistic = ${stat}, stars = FALSE, fmt = 3, ` +
    'gof_map = c("nobs", "r.squared", "adj.r.squared", "aic", "bic", "logLik", "rmse"), output = "markdown")'
}

export function ggsaveOrPrint(plotExpr: string): string {
  return `print(${plotExpr})`
}
