# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("car", "effectsize", "emmeans", "ggplot2"))
library(car)
library(effectsize)
library(emmeans)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$group <- factor(d$group)

# === 01 · ANCOVA ===
ac <- data.frame(y = d[["outcome"]], cov_1 = d[["baseline"]], fac_1 = factor(d[["group"]]))
ctr <- list(fac_1 = "contr.sum")
m <- lm(y ~ cov_1 + fac_1, data = ac, contrasts = ctr)
a3 <- car::Anova(m, type = 3)
print(a3)
print(effectsize::eta_squared(a3, partial = TRUE))
emm <- emmeans::emmeans(m, ~ fac_1, level = 0.95)
print(emm)
print(summary(pairs(emm, adjust = "tukey"), infer = TRUE, level = 0.95))
emm_df <- as.data.frame(emm)
gc <- setdiff(names(emm_df), c("emmean", "SE", "df", "lower.CL", "upper.CL"))
emm_df$g_lbl <- if (length(gc) > 1) do.call(paste, c(emm_df[gc], sep = " × ")) else as.character(emm_df[[gc[1]]])
print(ggplot(emm_df, aes(g_lbl, emmean)) +
  geom_pointrange(aes(ymin = lower.CL, ymax = upper.CL), colour = "#0c447c") + labs(x = NULL, y = NULL))