# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("lavaan", "semTools", "psych", "semPlot"))
library(lavaan)
library(semTools)
library(psych)
library(semPlot)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)

# === 01 · Path analysis ===
# No constructs defined — nothing to run for CB-SEM.