# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("vars"))
library(vars)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$month <- factor(d$month)

# === 01 · VAR ===
dd_ord <- d[order(d$month), ]
vdf <- dd_ord[, c("sales", "visitors")]
# Lag selection (search bound capped so models stay identified)
safe_max <- max(1L, min(10L, floor((nrow(vdf) - 1L) / ncol(vdf))))
sel <- vars::VARselect(vdf, lag.max = safe_max, type = 'const')
print(sel$selection); print(sel$criteria)
selected_lag <- as.integer(which.min(sel$criteria[1, ]))  # AIC minimum
fit <- vars::VAR(vdf, p = selected_lag, type = 'const')
# Per-equation coefficients (each equation is an lm)
for (eq in names(fit$varresult)) { cat("\n== Equation:", eq, "==\n"); print(summary(fit$varresult[[eq]])$coefficients); print(confint(fit$varresult[[eq]])) }
# Forecast-error variance decomposition at the IRF horizon
print(vars::fevd(fit, n.ahead = 10))
# Stability — max companion-eigenvalue modulus (< 1 = stable)
print(max(vars::roots(fit)))
# Figure — impulse-response functions
plot(vars::irf(fit, n.ahead = 10, boot = TRUE))