# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("lavaan", "semTools", "psych", "semPlot"))
library(lavaan)
library(semTools)
library(psych)
library(semPlot)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)

# === 01 · CB-SEM ===
# ---- CB-SEM via lavaan::sem (measurement + structural + indirect + moderation) ----
model_str <- "esg =~ esg1 + esg2 + esg3 + esg4\nnorm =~ norm1 + norm2 + norm3 + norm4\nservice_quality =~ service_quality1 + service_quality2 + service_quality3 + service_quality4\nattitude =~ attitude1 + attitude2 + attitude3 + attitude4\nintent =~ intent1 + intent2 + intent3\nintent ~ p_1_5*esg + p_2_5*norm + p_3_5*service_quality + pmod_1*attitude + pint_1*INT_1\nINT_1 =~ norm1.attitude1 + norm2.attitude2 + norm3.attitude3 + norm4.attitude4\nattitude ~~ vmod_1*attitude\nslope_lo_1  := p_2_5 - pint_1*sqrt(vmod_1)\nslope_mid_1 := p_2_5\nslope_hi_1  := p_2_5 + pint_1*sqrt(vmod_1)"

# ---- Latent moderation: indProd double-mean-centering data prep ----
mod_ids <- c(1)
mod_var1_flat <- c("norm1", "norm2", "norm3", "norm4")
mod_var1_lens <- c(4)
mod_var2_flat <- c("attitude1", "attitude2", "attitude3", "attitude4")
mod_var2_lens <- c(4)
mod_matched <- c(TRUE)

# Defensive defaults: the WebR call site (runCbSem.ts) deliberately OMITS these vars from the env
# object on a non-moderation run rather than sending empty JS arrays -- webr's JS->R env marshalling
# misdetects an empty array as tabular "array of row-objects" data (Array.prototype.every is vacuously
# true on []) and crashes converting it to a data.frame. R defines its own empty typed vectors instead.
if (!exists('mod_ids', inherits = FALSE)) {
  mod_ids <- integer(0); mod_var1_flat <- character(0); mod_var1_lens <- integer(0)
  mod_var2_flat <- character(0); mod_var2_lens <- integer(0); mod_matched <- logical(0)
  mod_target <- character(0)
}
if (length(mod_ids) > 0) {
  suppressMessages(library(semTools))
  v1_start <- 1L; v2_start <- 1L
  for (mi in seq_along(mod_ids)) {
    v1 <- mod_var1_flat[v1_start:(v1_start + mod_var1_lens[mi] - 1L)]; v1_start <- v1_start + mod_var1_lens[mi]
    v2 <- mod_var2_flat[v2_start:(v2_start + mod_var2_lens[mi] - 1L)]; v2_start <- v2_start + mod_var2_lens[mi]
    d <- indProd(d, var1 = v1, var2 = v2, match = as.logical(mod_matched[mi]), meanC = TRUE, doubleMC = TRUE)
  }
}


# Single awaited bootstrap fit for mediation/moderation (no RNG chunking - preserves WebR≡native parity).
gc()
set.seed(20260620)
fit <- lavaan::sem(model_str, data = d, se = "bootstrap", bootstrap = 1000)
# Dual CI (percentile + bias-corrected) from the SAME bootstrap draws - both recompute CIs off
# fit@boot without re-running the bootstrap (design §A2; matches runCbSem.ts exactly).
pe_perc <- lavaan::parameterEstimates(fit, boot.ci.type = "perc", level = 0.95)
pe_bc   <- lavaan::parameterEstimates(fit, boot.ci.type = "bca.simple", level = 0.95)
pe <- pe_perc
gc()
ss <- lavaan::standardizedSolution(fit)

# Row alignment by (lhs, rhs) key WITHIN an op-filtered subset, never by row position -- pe/pe_bc
# are TWO separate parameterEstimates() calls (perc vs bca.simple); the moderation spike (docs/
# superpowers/reviews/2026-07-06-moderation-spike.md §5.3) found position drift is not safe to
# assume across them. Scoped to a single op (e.g. "~") so the key is unique -- keying the FULL
# table would collide on every unlabeled row (label == "" for most non-structural parameters).
pair_key <- function(dfr) paste(dfr$lhs, dfr$rhs, sep = "\u0001")

# ---- Table 3: Measurement model (CFA) - B / SE / z / p / Std. loading ----
cat("\n--- Table 3: Measurement model (CFA) ---\n")
print(ss[ss$op == "=~", c("lhs","rhs","est.std")])

# ---- Table 4: Reliability & validity - CR / AVE / ω / α ----
# Do NOT call semTools::reliability() - deprecated 2022.
# Fit a SEPARATE continuous CFA for reliability (matches the app card exactly) - the structural
# fit above may carry estimator = "WLSMV"/ordered =, which compRelSEM cannot safely reuse.
model_rel_str <- "esg =~ esg1 + esg2 + esg3 + esg4\nnorm =~ norm1 + norm2 + norm3 + norm4\nservice_quality =~ service_quality1 + service_quality2 + service_quality3 + service_quality4\nattitude =~ attitude1 + attitude2 + attitude3 + attitude4\nintent =~ intent1 + intent2 + intent3"
fit_rel <- lavaan::cfa(model_rel_str, data = d, std.lv = FALSE)
cr_vec  <- unlist(semTools::compRelSEM(fit_rel))
ave_vec <- semTools::AVE(fit_rel)
cat("\n--- Table 4: Reliability & validity ---\n")
print(round(rbind(CR = cr_vec, AVE = ave_vec[names(cr_vec)]), 3))

# ---- Table 5: Fit indices (suppressed strictly when df == 0 - saturated) ----
# Shared predicate: byte-identical to the app screen (src/lib/stats/semSaturation.ts R_SATURATED_PREDICATE).
if (!(as.numeric(lavaan::fitMeasures(fit, "df")) == 0)) {
  fm <- lavaan::fitMeasures(fit, c("chisq","df","pvalue","cfi","tli","rmsea",
                                   "rmsea.ci.lower","rmsea.ci.upper","srmr"))
  cat("\n--- Table 5: Fit indices ---\n")
  print(round(fm, 3))
} else {
  cat("\n--- Model is saturated (df = 0): fit indices not reported ---\n")
}

# ---- Table 6: Structural paths (B / SE / z / p / std.β + dual 95% CI: percentile & bias-corrected) ----
# Scoped to the DRAWN paths' own p_<from>_<to> labels (buildModel labels every drawn structural path
# this way, and ONLY those) -- matches runCbSem.ts's struct_rows, which iterates the drawn path_from/
# path_to arrays rather than filtering by bare op == "~".
# Moderation note: bare `op == "~"` would ALSO match the interaction row (already reported in
# Table 8) and, when the moderator is not itself a drawn path, an auto-injected moderator
# main-effect covariate row that the app never surfaces anywhere -- this scoping excludes both,
# mirroring the app exactly (that covariate is part of the fitted model but reported in no table).
pe_reg <- pe[pe$op == "~" & grepl("^p_", pe$label), ]
pe_bc_reg <- pe_bc[pe_bc$op == "~" & grepl("^p_", pe_bc$label), ]
ss_reg <- ss[ss$op == "~" & grepl("^p_", ss$label), ]
reg_key <- pair_key(pe_reg)
rownames(pe_bc_reg) <- pair_key(pe_bc_reg); rownames(ss_reg) <- pair_key(ss_reg)
struct_tab <- data.frame(
  lhs = pe_reg$lhs, rhs = pe_reg$rhs, label = pe_reg$label,
  est = pe_reg$est, se = pe_reg$se, z = pe_reg$z, pvalue = pe_reg$pvalue,
  std = ss_reg[reg_key, "est.std"],
  perc.lower = pe_reg$ci.lower, perc.upper = pe_reg$ci.upper,
  bc.lower = pe_bc_reg[reg_key, "ci.lower"], bc.upper = pe_bc_reg[reg_key, "ci.upper"]
)
cat("\n--- Table 6: Structural paths ---\n")
print(struct_tab)
cat("\n--- R-square (endogenous) ---\n")
print(round(lavInspect(fit, "rsquare"), 3))

# ---- Table 8: Moderation (interaction-term B / SE / z / p / std.β + dual 95% CI) ----
pe_mod <- pe[pe$op == "~" & grepl("^INT_", pe$rhs), ]
pe_bc_mod <- pe_bc[pe_bc$op == "~" & grepl("^INT_", pe_bc$rhs), ]
ss_mod <- ss[ss$op == "~" & grepl("^INT_", ss$rhs), ]
mod_key <- pair_key(pe_mod)
rownames(pe_bc_mod) <- pair_key(pe_bc_mod); rownames(ss_mod) <- pair_key(ss_mod)
mod_tab <- data.frame(
  lhs = pe_mod$lhs, rhs = pe_mod$rhs, label = pe_mod$label,
  est = pe_mod$est, se = pe_mod$se, z = pe_mod$z, pvalue = pe_mod$pvalue,
  std = ss_mod[mod_key, "est.std"],
  perc.lower = pe_mod$ci.lower, perc.upper = pe_mod$ci.upper,
  bc.lower = pe_bc_mod[mod_key, "ci.lower"], bc.upper = pe_bc_mod[mod_key, "ci.upper"]
)
cat("\n--- Table 8: Moderation ---\n")
print(mod_tab)

# ---- Table 9: Conditional effects (simple slopes at -1SD/mean/+1SD, percentile 95% CI) ----
# Percentile CI only (binding contract, matches the app's conditional-effects table exactly).
slope_tab <- pe[pe$op == ":=" & grepl("^slope_", pe$lhs), c("lhs", "est", "se", "pvalue", "ci.lower", "ci.upper")]
names(slope_tab)[names(slope_tab) == "ci.lower"] <- "perc.lower"
names(slope_tab)[names(slope_tab) == "ci.upper"] <- "perc.upper"
cat("\n--- Table 9: Conditional effects (simple slopes) ---\n")
print(slope_tab)

# ---- Figure: path diagram (reproducible stand-in for the app-drawn annotated SVG) ----
semPlot::semPaths(fit, what = "std", layout = "tree", edge.label.cex = 0.9,
                  nodeLabels = NULL, residuals = FALSE, intercepts = FALSE)

# Note: semPaths draws the interaction construct's own path like any other structural path (no
# distinct "moderation" edge style) -- this is the closest reproducible native-R rendering; the app's
# live canvas draws it as a dashed clay arrow (see figure_path-diagram.png from the app export).