# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("effectsize", "ggplot2"))
library(effectsize)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$school <- factor(d$school)
d$classroom <- factor(d$classroom)

# === 01 · Nested ANOVA ===
af <- factor(d[["school"]]); bf <- factor(d[["classroom"]])  # named factors keep clean summary row names af / af:bf
m <- aov(d[["outcome"]] ~ af / bf)
s <- summary(m)[[1]]; rownames(s) <- trimws(rownames(s))
msA <- s["af", "Mean Sq"]; msB <- s["af:bf", "Mean Sq"]; msR <- s["Residuals", "Mean Sq"]
dfA <- s["af", "Df"]; dfB <- s["af:bf", "Df"]; dfR <- s["Residuals", "Df"]
fA <- msA / msB; pA <- pf(fA, dfA, dfB, lower.tail = FALSE)  # random nesting: A tested against B(A)
fB <- msB / msR; pB <- pf(fB, dfB, dfR, lower.tail = FALSE)
print(data.frame(source = c("A", "B"), F = c(fA, fB), p = c(pA, pB)))
print(effectsize::omega_squared(m, partial = FALSE))
cellm <- aggregate(list(m = d[["outcome"]]), by = list(a = af, b = bf), FUN = mean)
nc <- aggregate(list(n = d[["outcome"]]), by = list(a = af, b = bf), FUN = length)
sdv <- aggregate(list(s = d[["outcome"]]), by = list(a = af, b = bf), FUN = sd)
cellm$lo <- cellm$m - qt(0.975, nc$n - 1) * sdv$s / sqrt(nc$n)
cellm$hi <- cellm$m + qt(0.975, nc$n - 1) * sdv$s / sqrt(nc$n)
print(ggplot(cellm, aes(a, m, colour = b)) +
  geom_pointrange(aes(ymin = lo, ymax = hi), position = position_dodge(width = 0.5)) + labs(x = NULL, y = NULL, colour = NULL))