# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("forecast", "ggplot2"))
library(forecast)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$month <- factor(d$month)

# === 01 · ARIMA / SARIMA ===
# sort by time so the series is in order
dd_ord <- d[order(d$month), ]
x_ts <- ts(dd_ord$sales, frequency = 12)
fit <- forecast::auto.arima(x_ts)
print(fit)
print(confint(fit, level = 0.95))
print(Box.test(residuals(fit), type = "Ljung-Box"))
print(c(AIC = AIC(fit), BIC = BIC(fit), logLik = as.numeric(logLik(fit)), sigma2 = fit$sigma2))
# Forecast table + figure
fc <- forecast::forecast(fit, h = 12, level = c(80, 95))
print(fc)
print(forecast::autoplot(fc) + labs(x = "month", y = "sales") + theme_minimal())
# Residual diagnostics — residual ACF + Normal Q-Q
r <- as.numeric(residuals(fit)); nn <- length(r); ac <- acf(r, plot = FALSE)
panels <- rbind(
  data.frame(panel = "Residual ACF", x = as.numeric(ac$lag[-1]), y = as.numeric(ac$acf[-1])),
  data.frame(panel = "Normal Q-Q", x = qnorm(ppoints(nn)), y = sort(r)))
panels$panel <- factor(panels$panel, levels = c("Residual ACF", "Normal Q-Q"))
qs <- quantile(r, c(0.25, 0.75)); zs <- qnorm(c(0.25, 0.75)); slope <- diff(qs) / diff(zs)
refs <- data.frame(panel = factor(c("Residual ACF", "Normal Q-Q"), levels = levels(panels$panel)),
                   slope = c(0, slope), intercept = c(0, qs[1] - slope * zs[1]))
print(ggplot(panels, aes(x, y)) +
  geom_abline(data = refs, aes(slope = slope, intercept = intercept), colour = "#9cc2ec", linetype = "dashed") +
  geom_point(colour = "#0c447c") + facet_wrap(~panel, scales = "free") + labs(x = NULL, y = NULL))