# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("modelsummary", "ggplot2", "parameters", "car"))
library(modelsummary)
library(ggplot2)
library(parameters)
library(car)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$group <- factor(d$group)
d$method <- factor(d$method)

# === 01 · Multiple linear regression ===
m <- lm(post_score ~ pre_score + age + group + method, data = d)
modelsummary(list("(1)" = m), statistic = c("std.error", "conf.int"), stars = FALSE, fmt = 3, gof_map = c("nobs", "r.squared", "adj.r.squared", "aic", "bic", "logLik", "rmse"), output = "markdown")
# standardized betas + VIF (display extras)
print(parameters::standardise_parameters(m, method = "refit"))
print(car::vif(m))
# Figure 1 — residual diagnostics (fitted-vs-residual + Normal Q-Q)
r <- residuals(m); fv <- fitted(m); nn <- length(r)
panels <- rbind(
  data.frame(panel = "Residuals vs fitted", x = fv, y = r),
  data.frame(panel = "Normal Q-Q", x = qnorm(ppoints(nn)), y = sort(r)))
panels$panel <- factor(panels$panel, levels = c("Residuals vs fitted", "Normal Q-Q"))
qs <- quantile(r, c(0.25, 0.75)); zs <- qnorm(c(0.25, 0.75)); slope <- diff(qs) / diff(zs)
refs <- data.frame(panel = factor(c("Residuals vs fitted", "Normal Q-Q"), levels = levels(panels$panel)),
                   slope = c(0, slope), intercept = c(0, qs[1] - slope * zs[1]))
print(ggplot(panels, aes(x, y)) +
  geom_abline(data = refs, aes(slope = slope, intercept = intercept), colour = "#9cc2ec", linetype = "dashed") +
  geom_point(colour = "#0c447c") + facet_wrap(~panel, scales = "free") + labs(x = NULL, y = NULL))
# Figure 2 — standardized coefficient plot (95% CI), intercept excluded
sp <- parameters::standardise_parameters(m, method = "refit", ci = 0.95)
sp <- sp[sp$Parameter != "(Intercept)", ]
sp$Parameter <- factor(sp$Parameter, levels = rev(sp$Parameter))
print(ggplot(sp, aes(x = Std_Coefficient, y = Parameter)) +
  geom_vline(xintercept = 0, colour = "#9cc2ec", linetype = "dashed") +
  geom_pointrange(aes(xmin = CI_low, xmax = CI_high), colour = "#0c447c") +
  labs(x = paste0("Standardized \u03b2 (", round(0.95 * 100), "% CI)"), y = NULL))