# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("ggplot2"))
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$group <- factor(d$group)

# === 01 · MANOVA ===
m <- manova(cbind(d[["outcome"]], d[["outcome2"]]) ~ factor(d[["group"]]))
print(summary(m, test = "Pillai"))
print(summary(aov(d[["outcome"]] ~ factor(d[["group"]]))))
print(summary(aov(d[["outcome2"]] ~ factor(d[["group"]]))))
gf <- factor(d[["group"]])
agg <- do.call(rbind, lapply(list(c(d[["outcome"]]), c(d[["outcome2"]])), function(v) {
  mm <- tapply(v, gf, mean); nn <- tapply(v, gf, length); ss <- tapply(v, gf, sd)
  se <- ss / sqrt(nn); tq <- qt(0.975, nn - 1)
  data.frame(g = names(mm), m = as.numeric(mm), lo = as.numeric(mm - tq * se), hi = as.numeric(mm + tq * se)) }))
agg$dv <- rep(c("outcome", "outcome2"), each = nlevels(gf))
print(ggplot(agg, aes(g, m)) + geom_pointrange(aes(ymin = lo, ymax = hi), colour = "#0c447c") +
  facet_wrap(~dv, scales = "free_y") + labs(x = NULL, y = NULL))