# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("lavaan", "semTools", "psych", "ggplot2"))
library(lavaan)
library(semTools)
library(psych)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)

# === 01 · Composite reliability (CR) ===
# ---- Composite Reliability (CR) / ω / AVE / α via lavaan + semTools + psych ----
construct_names <- c("visual", "textual", "speed")
k <- length(construct_names)

model_str <- "visual =~ x1 + x2 + x3\ntextual =~ x4 + x5 + x6\nspeed =~ x7 + x8 + x9"

# Fit CFA
fit <- lavaan::cfa(model_str, data = d, std.lv = FALSE)

# CR (= ω for congeneric) and AVE per construct
# Do NOT call semTools::reliability() — deprecated 2022.
cr_vec  <- unlist(semTools::compRelSEM(fit))
ave_vec <- semTools::AVE(fit)

# Per-construct Cronbach's α via psych::alpha
construct_items_flat <- c("x1", "x2", "x3", "x4", "x5", "x6", "x7", "x8", "x9")
construct_items_lens <- c(3, 3, 3)
alpha_vec <- numeric(k)
item_start <- 1L
for (ci in seq_len(k)) {
  len <- construct_items_lens[ci]
  citems <- construct_items_flat[item_start:(item_start + len - 1L)]
  item_start <- item_start + len
  a_obj <- psych::alpha(d[, citems, drop = FALSE], warnings = FALSE)
  alpha_vec[ci] <- a_obj$total$raw_alpha
}

# Print T1: Composite reliability
cat("\n--- Table 1: Composite reliability ---\n")
for (ci in seq_len(k)) {
  nm <- construct_names[ci]
  cat(sprintf("  %s: CR=%.3f AVE=%.3f omega=%.3f alpha=%.3f\n",
              nm, cr_vec[nm], ave_vec[nm], cr_vec[nm], alpha_vec[ci]))
}

# Figure: CR bar chart
d_plot <- data.frame(
  construct = factor(construct_names, levels = rev(construct_names)),
  value     = as.numeric(cr_vec[construct_names])
)
print(
  ggplot2::ggplot(d_plot, ggplot2::aes(x = value, y = construct)) +
  ggplot2::geom_col(fill = "#0c447c") +
  ggplot2::geom_vline(xintercept = 0.7, linetype = "dashed", colour = "#9cc2ec") +
  ggplot2::labs(x = "CR", y = NULL) +
  ggplot2::theme(legend.position = "none")
)