# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("plm", "lmtest", "ggplot2"))
library(plm)
library(lmtest)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$firm <- factor(d$firm)

# === 01 · Hausman test ===
pdat <- plm::pdata.frame(d, index = c("firm", "year"))
fe <- plm::plm(roa ~ leverage + rd_spend + size, data = pdat, model = 'within')
re <- plm::plm(roa ~ leverage + rd_spend + size, data = pdat, model = 'random')
print(plm::phtest(fe, re))
# clustered (arellano/HC1) SE + 95% CI per model on the common FE slopes
fe_vc <- plm::vcovHC(fe, method = 'arellano', type = 'HC1', cluster = 'group')
re_vc <- plm::vcovHC(re, method = 'arellano', type = 'HC1', cluster = 'group')
terms <- names(coef(fe))
fe_ci <- lmtest::coefci(fe, vcov. = fe_vc, level = 0.95)
re_ci <- lmtest::coefci(re, vcov. = re_vc, level = 0.95)
cmp <- data.frame(term = terms, FE = unname(coef(fe)[terms]), RE = unname(coef(re)[terms]),
                  Difference = unname(coef(fe)[terms] - coef(re)[terms]))
print(cmp)
# Figure — side-by-side FE vs RE coefficient plot (clustered 95% CIs, dodged)
pdat2 <- rbind(
  data.frame(term = terms, model = "FE", est = unname(coef(fe)[terms]), lo = fe_ci[terms, 1], hi = fe_ci[terms, 2]),
  data.frame(term = terms, model = "RE", est = unname(coef(re)[terms]), lo = re_ci[terms, 1], hi = re_ci[terms, 2]))
pdat2$term <- factor(pdat2$term, levels = rev(terms))
print(ggplot(pdat2, aes(x = est, y = term, colour = model)) +
  geom_vline(xintercept = 0, colour = "#9cc2ec", linetype = "dashed") +
  geom_pointrange(aes(xmin = lo, xmax = hi), position = position_dodge(width = 0.4)) +
  scale_colour_manual(values = c(FE = "#0c447c", RE = "#c8781e")) +
  labs(x = "Estimate (95% CI)", y = NULL, colour = NULL))