# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("rdrobust"))
library(rdrobust)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)

# === 01 · Regression discontinuity (RDD) ===
rd <- rdrobust::rdrobust(d$score, d$running_var, c = 50, p = 1, level = 95)
print(summary(rd))
# Figure — RD plot (binned scatter + fitted lines either side of the cutoff)
print(rdrobust::rdplot(d$score, d$running_var, c = 50, hide = TRUE)$rdplot)