# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("rdrobust"))
library(rdrobust)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)

# === 01 · Regression discontinuity (RDD) ===
rd <- rdrobust::rdrobust(d$later_gpa, d$entrance_score, c = 60, p = 1, level = 95)
print(summary(rd))
# Bandwidth-sensitivity re-estimates at half/double the MSE-optimal h (R1 gap-fix)
h0 <- rd$bws[1, 1]
print(summary(rdrobust::rdrobust(d$later_gpa, d$entrance_score, c = 60, p = 1, level = 95, h = h0 / 2)))
print(summary(rdrobust::rdrobust(d$later_gpa, d$entrance_score, c = 60, p = 1, level = 95, h = h0 * 2)))
# Figure — RD plot (binned scatter + fitted lines either side of the cutoff)
print(rdrobust::rdplot(d$later_gpa, d$entrance_score, c = 60, hide = TRUE)$rdplot)