# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("ggplot2"))
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$passed <- factor(d$passed)
d$gender <- factor(d$gender)

# === 01 · Fisher's exact ===
sub <- d[!is.na(d[["passed"]]) & trimws(d[["passed"]]) != "" & !is.na(d[["gender"]]) & trimws(d[["gender"]]) != "", ]
tab <- table(sub[["passed"]], sub[["gender"]])
print(fisher.test(tab, alternative = "two.sided"))
print(ggplot(sub, aes(passed, fill = gender)) + geom_bar(position = "dodge"))