# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("lmtest", "ggplot2"))
library(lmtest)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$month <- factor(d$month)

# === 01 · Granger causality ===
dd_ord <- d[order(d$month), ]
# X -> Y: does ad_spend Granger-cause sales?
print(lmtest::grangertest(d$sales ~ d$ad_spend, order = 4))
# Y -> X: does sales Granger-cause ad_spend?
print(lmtest::grangertest(d$ad_spend ~ d$sales, order = 4))
# Figure — cross-series time plot
nn <- nrow(dd_ord); idx <- seq_len(nn)
gdf <- rbind(data.frame(t = idx, value = dd_ord$ad_spend, series = "ad_spend"),
             data.frame(t = idx, value = dd_ord$sales, series = "sales"))
gdf$series <- factor(gdf$series, levels = c("ad_spend", "sales"))
print(ggplot(gdf, aes(x = t, y = value, colour = series)) + geom_line() +
  scale_colour_manual(values = c("#0c447c", "#e07020")) +
  labs(x = "month", y = NULL, colour = NULL) + theme_minimal() + theme(legend.position = "top"))