# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("ggplot2"))
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)

# === 01 · Spearman correlation ===
ct <- suppressWarnings(cor.test(d[["motivation_1"]], d[["exam_score"]], method = "spearman", exact = FALSE, alternative = "two.sided"))
print(ct)
print(ggplot(d, aes(motivation_1, exam_score)) + geom_point())