# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("plm", "lmtest", "ggplot2"))
library(plm)
library(lmtest)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$firm <- factor(d$firm)

# === 01 · Difference-in-differences (DiD) ===
# code treated/post to 0/1 by the positive level (avoids the pre<post sign flip)
d$tr <- ifelse(as.character(d$treated) == "1", 1, 0)
d$po <- ifelse(as.character(d$post) == "1", 1, 0)
pdat <- plm::pdata.frame(data.frame(.entity = d$firm, .timev = d$year, roa = d$roa, po = d$po, tr = d$tr), index = c(".entity", ".timev"))
fit <- plm::plm(roa ~ po + po:tr, data = pdat, model = 'within')
V <- plm::vcovHC(fit, method = 'arellano', type = 'HC1', cluster = 'group')
print(lmtest::coeftest(fit, vcov. = V))
print(lmtest::coefci(fit, vcov. = V, level = 0.95))
print(summary(fit))
# Figure — parallel-trends plot (group means over time, treatment onset marked)
# mirror did.ts: aggregate over LISTWISE-complete rows; rank a non-numeric time axis to integer order
keep <- is.finite(suppressWarnings(as.numeric(d$roa))) &
  !is.na(d$treated) & trimws(as.character(d$treated)) != "" &
  !is.na(d$post) & trimws(as.character(d$post)) != "" &
  !is.na(d$firm) & trimws(as.character(d$firm)) != "" &
  !is.na(d$year) & trimws(as.character(d$year)) != ""
df_t <- d[keep, ]
raw_time <- df_t$year
tt <- if (is.numeric(raw_time) && all(is.finite(raw_time))) raw_time else match(as.character(raw_time), sort(unique(as.character(raw_time))))
agg <- aggregate(yy ~ tt + grp, data = data.frame(yy = df_t$roa, tt = tt, grp = ifelse(df_t$tr == 1, "Treated", "Control")), FUN = mean)
onset <- min(tt[df_t$po == 1])
print(ggplot(agg, aes(x = tt, y = yy, colour = grp, group = grp)) +
  geom_vline(xintercept = onset, colour = "#9cc2ec", linetype = "dashed") +
  geom_line() + geom_point() +
  scale_colour_manual(values = c(Control = "#0c447c", Treated = "#c8781e")) +
  labs(x = "Time", y = "Mean outcome", colour = NULL))