# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("plm", "lmtest", "ggplot2"))
library(plm)
library(lmtest)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d[["province"]] <- factor(d[["province"]])

# === 01 · Random effects ===
pdat <- plm::pdata.frame(d, index = c("province", "year"))
fit <- plm::plm(growth ~ investment + education_spend + urbanization, data = pdat, model = 'random')
V <- plm::vcovHC(fit, method = 'arellano', type = 'HC1', cluster = 'group')
print(lmtest::coeftest(fit, vcov. = V))
print(lmtest::coefci(fit, vcov. = V, level = 0.95))
print(summary(fit))
# Within/between/overall R2 (Stata xtreg convention, R1 gap-fix) - additive alongside plm's own R2/R2 Adj.
b_re <- coef(fit)
xb <- b_re[["(Intercept)"]] + as.numeric(as.matrix(d[, c("investment", "education_spend", "urbanization"), drop = FALSE]) %*% b_re[c("investment", "education_spend", "urbanization")])
id2 <- d$province
dm2 <- function(v) ave(v, id2, FUN = function(x) x - mean(x))
cat("Within R2:", cor(dm2(d$growth), dm2(xb))^2, "\n")
agg <- aggregate(cbind(yy, xbxb) ~ idid, data.frame(idid = id2, yy = d$growth, xbxb = xb), mean)
cat("Between R2:", cor(agg$yy, agg$xbxb)^2, "\n")
cat("Overall R2:", cor(d$growth, xb)^2, "\n")
# Figure - coefficient plot (95% CI), intercept excluded
ci <- lmtest::coefci(fit, vcov. = V, level = 0.95); est <- coef(fit); labs <- names(est)
keep <- labs != "(Intercept)"
pf <- data.frame(term = factor(labs[keep], levels = rev(labs[keep])), b = unname(est[keep]), lo = ci[keep, 1], hi = ci[keep, 2])
print(ggplot(pf, aes(x = b, y = term)) +
  geom_vline(xintercept = 0, colour = "#9cc2ec", linetype = "dashed") +
  geom_pointrange(aes(xmin = lo, xmax = hi), colour = "#0c447c") +
  labs(x = "Estimate (95% CI)", y = NULL))