# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("seminr"))
library(seminr)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)

# === 01 · PLS-SEM ===
# ---- PLS-SEM via seminr (estimate_pls + bootstrap_model) ----
# WebR/WASM has no PSOCK sockets - install the serial-cluster shim before seminr bootstraps.
local({
  ns <- asNamespace("parallel")
  mk <- function(...) structure(list(), class = c("telosSerialCluster", "SOCKcluster", "cluster"))
  for (fn in c("makeCluster","makePSOCKcluster","makeForkCluster")) if (exists(fn, ns)) { unlockBinding(fn, ns); assign(fn, mk, ns) }
  unlockBinding("parLapply", ns)
  assign("parLapply", function(cl, X, fun, ...) { a <- list(...); a[["chunk.size"]] <- NULL; do.call(base::lapply, c(list(X = X, FUN = fun), a)) }, ns)
  if (exists("parSapply", ns)) { unlockBinding("parSapply", ns); assign("parSapply", function(cl, X, fun, ...) { a <- list(...); a[["chunk.size"]] <- NULL; do.call(base::sapply, c(list(X = X, FUN = fun), a)) }, ns) }
  for (fn in c("clusterExport","clusterEvalQ","clusterCall","clusterApply","clusterApplyLB","stopCluster","clusterSetRNGStream")) if (exists(fn, ns)) { unlockBinding(fn, ns); assign(fn, function(...) invisible(NULL), ns) }
})
library(seminr)

# Hand-rolled z0-adjusted percentile BC (U6-T3) - reused verbatim from the lavaan-verified text
# (src/lib/stats/plsBcCi.ts); seminr has no built-in bca.simple, so bc_ci() runs here against
# bo$boot_paths' raw draws (a [from, to, boot_index] 3D array).

norm_inter <- function(t, alpha) {
  t <- t[is.finite(t)]; R <- length(t)
  rk <- (R + 1) * alpha
  k <- trunc(rk)
  tstar <- sort(t)
  out <- numeric(length(k))
  for (j in seq_along(k)) {
    if (k[j] == rk[j])      out[j] <- tstar[k[j]]
    else if (k[j] == 0)     out[j] <- tstar[1]
    else if (k[j] == R)     out[j] <- tstar[R]
    else {
      temp1 <- qnorm(alpha[j]); temp2 <- qnorm(k[j] / (R + 1)); temp3 <- qnorm((k[j] + 1) / (R + 1))
      out[j] <- tstar[k[j]] + (temp1 - temp2) / (temp3 - temp2) * (tstar[k[j] + 1] - tstar[k[j]])
    }
  }
  out
}
bc_ci <- function(draws, t0, level = 0.95) {
  draws <- draws[is.finite(draws)]
  zalpha <- qnorm((1 + c(-level, level)) / 2)
  w <- qnorm(sum(draws < t0) / length(draws))
  norm_inter(draws, pnorm(2 * w + zalpha))
}


# Measurement model (reflective = mode_A; formative = mode_B)
mm <- constructs(
  composite("esg", c("esg1", "esg2", "esg3", "esg4"), weights = mode_A),
  composite("norm", c("norm1", "norm2", "norm3", "norm4"), weights = mode_A),
  composite("service_quality", c("service_quality1", "service_quality2", "service_quality3", "service_quality4"), weights = mode_A),
  composite("attitude", c("attitude1", "attitude2", "attitude3", "attitude4"), weights = mode_A),
  composite("intent", c("intent1", "intent2", "intent3"), weights = mode_A),
  interaction_term(iv = "norm", moderator = "attitude", method = two_stage, weights = mode_A)
)

# Structural model (paths by construct name)
sm <- relationships(
  paths(from = "esg", to = "intent"),
  paths(from = "norm", to = "intent"),
  paths(from = "service_quality", to = "intent"),
  paths(from = "attitude", to = "intent"),
  paths(from = "norm*attitude", to = "intent")
)

# Moderation (U6-T4): interaction_term construct(s) added to the measurement model above.
cat("interaction_term(iv = \"norm\", moderator = \"attitude\", method = two_stage)\n")

# Estimate + bootstrap (percentile CI; serial cores under the shim)
gc()
pls <- estimate_pls(data = d, measurement_model = mm, structural_model = sm)
s <- summary(pls)
set.seed(20260620)
bo <- bootstrap_model(seminr_model = pls, nboot = 1000, cores = 1)
sb <- summary(bo)
gc()

# The DRAWN construct names only - excludes seminr's derived interaction construct (no meaningful
# alpha/AVE/HTMT/outer rows; its structural row still flows through the path loop below).
construct_names <- c("esg", "norm", "service_quality", "attitude", "intent")
formative_names <- c()

# ---- Table 1: Measurement model (construct alpha/rhoA/CR/AVE + item mean/sd/loading-or-weight/t/p) ----
# Raw seminr reliability order is alpha/rhoC/AVE/rhoA - reordered here to the display tuple.
rel <- s$reliability[, c("alpha", "rhoA", "rhoC", "AVE"), drop = FALSE]
if (length(formative_names)) rel[rownames(rel) %in% formative_names, "AVE"] <- NA
cat("\n--- Table 1: Measurement model ---\n")
for (nm in construct_names) {
  is_form <- nm %in% formative_names
  cat(sprintf("%s: alpha=%.3f rhoA=%.3f CR=%.3f AVE=%s\n",
              nm, rel[nm, "alpha"], rel[nm, "rhoA"], rel[nm, "rhoC"],
              if (is_form) "NA" else sprintf("%.3f", rel[nm, "AVE"])))
  items_nm <- pls$mmMatrix[pls$mmMatrix[, "construct"] == nm, "measurement"]
  for (it in items_nm) {
    key <- paste0(it, "  ->  ", nm)
    m <- mean(d[[it]], na.rm = TRUE); sdv <- sd(d[[it]], na.rm = TRUE)
    if (is_form) {
      w <- as.numeric(sb$bootstrapped_weights[key, "Original Est."])
      tval <- as.numeric(sb$bootstrapped_weights[key, "T Stat."])
      cat(sprintf("  %s: weight=%.3f t=%.3f p=%.4f mean=%.3f sd=%.3f\n",
                  it, w, tval, 2 * pnorm(-abs(tval)), m, sdv))
    } else {
      l <- as.numeric(sb$bootstrapped_loadings[key, "Original Est."])
      tval <- as.numeric(sb$bootstrapped_loadings[key, "T Stat."])
      cat(sprintf("  %s: loading=%.3f t=%.3f p=%.4f mean=%.3f sd=%.3f\n",
                  it, l, tval, 2 * pnorm(-abs(tval)), m, sdv))
    }
  }
}

# ---- Table 2: HTMT ----
cat("\n--- Table 2: HTMT ---\n")
print(round(s$validity$htmt[construct_names, construct_names, drop = FALSE], 3))

# ---- Table 3: Structural paths (β + t/p + dual 95% CI: percentile & hand-rolled BC) ----
bp <- sb$bootstrapped_paths
fsq <- s$fSquare
vif_ant <- s$vif_antecedents
path_from_all <- c("esg", "norm", "service_quality", "attitude", "norm*attitude")
path_to_all   <- c("intent", "intent", "intent", "intent", "intent")
struct_beta <- numeric(length(path_from_all)); struct_t <- numeric(length(path_from_all))
struct_p <- numeric(length(path_from_all))
struct_perc_lo <- numeric(length(path_from_all)); struct_perc_hi <- numeric(length(path_from_all))
struct_bc_lo <- numeric(length(path_from_all)); struct_bc_hi <- numeric(length(path_from_all))
for (e in seq_along(path_from_all)) {
  fr <- path_from_all[e]; to <- path_to_all[e]
  key <- paste0(fr, "  ->  ", to)
  beta_e <- as.numeric(bp[key, "Original Est."])
  tval_e <- as.numeric(bp[key, "T Stat."])
  bcc <- bc_ci(bo$boot_paths[fr, to, ], beta_e)
  struct_beta[e] <- beta_e; struct_t[e] <- tval_e; struct_p[e] <- 2 * pnorm(-abs(tval_e))
  struct_perc_lo[e] <- as.numeric(bp[key, "2.5% CI"]); struct_perc_hi[e] <- as.numeric(bp[key, "97.5% CI"])
  struct_bc_lo[e] <- as.numeric(bcc[1]); struct_bc_hi[e] <- as.numeric(bcc[2])
}
struct_tab <- data.frame(
  h = paste0("H", seq_along(path_from_all)),
  path = paste(path_from_all, "->", path_to_all),
  beta = struct_beta, t = struct_t, pvalue = struct_p,
  perc.lower = struct_perc_lo, perc.upper = struct_perc_hi,
  bc.lower = struct_bc_lo, bc.upper = struct_bc_hi
)
cat("\n--- Table 3: Structural paths ---\n")
print(struct_tab)

# ---- Table 3 (cont.): f² + inner VIF per path (R6; Hair, Risher, Sarstedt & Ringle 2019 -
# collinearity is checklist step 1, effect sizes step 4). These are Table 3 COLUMNS on the app
# card; printed as their own compact block here so the wide struct_tab data.frame stays stable.
# vif_ant is a named list keyed by endogenous construct; a single-antecedent target carries
# seminr's NA placeholder (the app renders a dash - collinearity is undefined with one predictor).
cat("\n--- Table 3 (cont.): inner VIF & f^2 per path ---\n")
for (e in seq_along(path_from_all)) {
  fr <- path_from_all[e]; to <- path_to_all[e]
  vif_e <- suppressWarnings(as.numeric(vif_ant[[to]][fr]))
  if (length(vif_e) == 0) vif_e <- NA
  vif_s <- if (is.na(vif_e)) "NA" else sprintf("%.6f", vif_e)
  cat(sprintf("  %s -> %s: f2=%.6f VIF=%s\n", fr, to, as.numeric(fsq[fr, to]), vif_s))
}

# ---- Table 4: Structural quality (R² / R²adj / Q²_predict) ----
paths_tbl <- s$paths
endo <- colnames(paths_tbl)
set.seed(20260620)
q2_pred <- tryCatch({
  pp <- predict_pls(pls)
  sp <- summary(pp)
  1 - sp$PLS_out_of_sample["RMSE", ]^2 / sp$LM_out_of_sample["RMSE", ]^2
}, error = function(e) NULL)
quality_tab <- data.frame(
  construct = endo,
  r2 = as.numeric(paths_tbl["R^2", endo]), r2adj = as.numeric(paths_tbl["AdjR^2", endo]),
  q2 = sapply(endo, function(nm) {
    if (is.null(q2_pred)) return(NA)
    its <- pls$mmMatrix[pls$mmMatrix[, "construct"] == nm, "measurement"]
    its <- its[its %in% names(q2_pred)]
    if (length(its)) mean(q2_pred[its]) else NA
  })
)
cat("\n--- Table 4: Structural quality (R^2 / AdjR^2 / Q^2_predict) ---\n")
print(round(quality_tab[, c("r2", "r2adj", "q2")], 4))

# ---- Table 5: Indirect effects (specific_effect_significance over each mediated triple) ----
# Interaction edges are skipped: the interaction construct is not a dimname of adj and never
# participates in a mediation chain (no incoming paths) - matches plsSem.ts's R block exactly.
cat("\n--- Table 5: Indirect effects ---\n")
k_cn <- length(construct_names)
adj <- matrix(FALSE, k_cn, k_cn, dimnames = list(construct_names, construct_names))
adj["esg", "intent"] <- TRUE
adj["norm", "intent"] <- TRUE
adj["service_quality", "intent"] <- TRUE
for (a in construct_names) for (z in construct_names) if (a != z) {
  for (m in construct_names[adj[a, ] & adj[, z]]) {
    sig <- tryCatch(specific_effect_significance(bo, from = a, through = m, to = z, alpha = 0.05),
                    error = function(e) NULL)
    if (!is.null(sig)) { cat(sprintf("  %s -> %s -> %s: ", a, m, z)); print(round(sig, 4)) }
  }
}

# ---- Table 6: Conditional effects (simple slopes at -1SD/mean/+1SD, percentile 95% CI) ----
# Same derivation as plsSem.ts's R block: mod_sd is the moderator's OBSERVED composite-score SD
# (Aiken & West 1991 applied to the composite/summed-indicator metric); levels are fixed at the
# original mod_sd for every bootstrap draw (draws differ only in the main/interaction path terms).
mod_iv_name <- c("norm")
mod_name    <- c("attitude")
mod_int_name <- c("norm*attitude")
mod_target_name <- c("intent")
ip_y_lo_lo <- numeric(0); ip_y_hi_lo <- numeric(0); ip_y_lo_hi <- numeric(0); ip_y_hi_hi <- numeric(0)
cat("\n--- Table 6: Conditional effects (simple slopes) ---\n")
for (mi in seq_along(mod_iv_name)) {
  mod_sd <- stats::sd(pls$construct_scores[, mod_name[mi]])
  key_main <- paste0(mod_iv_name[mi], "  ->  ", mod_target_name[mi])
  key_int  <- paste0(mod_int_name[mi], "  ->  ", mod_target_name[mi])
  b_main <- as.numeric(bp[key_main, "Original Est."])
  b_int  <- as.numeric(bp[key_int, "Original Est."])
  main_draws <- bo$boot_paths[mod_iv_name[mi], mod_target_name[mi], ]
  int_draws  <- bo$boot_paths[mod_int_name[mi], mod_target_name[mi], ]
  levels <- c("-1SD" = -mod_sd, "mean" = 0, "+1SD" = mod_sd)
  for (lvl_name in names(levels)) {
    lvl <- levels[[lvl_name]]
    draws <- main_draws + int_draws * lvl
    se <- stats::sd(draws)
    qs <- stats::quantile(draws, probs = c(0.025, 0.975))
    b_lvl <- b_main + b_int * lvl
    p_lvl <- 2 * min(mean(draws <= 0), mean(draws > 0))
    cat(sprintf("  %s (%s): b=%.6f se=%.6f p=%.6f ci=[%.6f, %.6f]\n",
                mod_int_name[mi], lvl_name, b_lvl, se, p_lvl, qs[1], qs[2]))
  }
  iv_sd <- stats::sd(pls$construct_scores[, mod_iv_name[mi]])
  b_mod <- as.numeric(bp[paste0(mod_name[mi], "  ->  ", mod_target_name[mi]), "Original Est."])
  slope_lo <- b_main - b_int * mod_sd
  slope_hi <- b_main + b_int * mod_sd
  ip_y_lo_lo <- c(ip_y_lo_lo, -iv_sd * slope_lo - b_mod * mod_sd)
  ip_y_hi_lo <- c(ip_y_hi_lo,  iv_sd * slope_lo - b_mod * mod_sd)
  ip_y_lo_hi <- c(ip_y_lo_hi, -iv_sd * slope_hi + b_mod * mod_sd)
  ip_y_hi_hi <- c(ip_y_hi_hi,  iv_sd * slope_hi + b_mod * mod_sd)
}

# ---- Figure: interaction plot (two-line Aiken-West chart; R4 owner ruling, default R styling) ----
# Same R text as interactionPlot.ts (export = app); replaces the pre-R4 whiskered simple-slopes plot.
ip_edge_labels <- paste0(mod_iv_name, " → ", mod_target_name, " × ", mod_name)
ip_iv_names <- mod_iv_name; ip_dv_names <- mod_target_name; ip_mod_names <- mod_name
n_edges <- length(ip_edge_labels)
if (n_edges > 1) par(mfrow = c(n_edges, 1))
for (ei in seq_len(n_edges)) {
  ys <- c(ip_y_lo_lo[ei], ip_y_hi_lo[ei], ip_y_lo_hi[ei], ip_y_hi_hi[ei])
  plot(c(-1, 1), ys[1:2], type = "o", pch = 16, lty = 1,
       xlim = c(-1.4, 1.4), ylim = grDevices::extendrange(ys),
       xaxt = "n", xlab = NA, ylab = ip_dv_names[ei],
       main = if (n_edges > 1) ip_edge_labels[ei] else NA)
  lines(c(-1, 1), ys[3:4], type = "o", pch = 15, lty = 2)
  axis(1, at = c(-1, 1), labels = paste(ip_iv_names[ei], c("-1 SD", "+1 SD")))
  legend("topleft", legend = paste(ip_mod_names[ei], c("-1 SD", "+1 SD")),
         lty = c(1, 2), pch = c(16, 15), bty = "n")
}
if (n_edges > 1) par(mfrow = c(1, 1))

# Figure: path diagram - semPaths stand-in (the app exports the annotated SVG via html-to-image)
cat("\n--- Figure: PLS path diagram (semPaths reproducible stand-in) ---\n")
tryCatch(print(plot(pls)), error = function(e) cat("(diagram skipped:", conditionMessage(e), ")\n"))