# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("seminr", "ggplot2"))
library(seminr)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)

# === 01 · PLS-SEM ===
# ---- PLS-SEM via seminr (estimate_pls + bootstrap_model) ----
# WebR/WASM has no PSOCK sockets — install the serial-cluster shim before seminr bootstraps.
local({
  ns <- asNamespace("parallel")
  mk <- function(...) structure(list(), class = c("telosSerialCluster", "SOCKcluster", "cluster"))
  for (fn in c("makeCluster","makePSOCKcluster","makeForkCluster")) if (exists(fn, ns)) { unlockBinding(fn, ns); assign(fn, mk, ns) }
  unlockBinding("parLapply", ns)
  assign("parLapply", function(cl, X, fun, ...) { a <- list(...); a[["chunk.size"]] <- NULL; do.call(base::lapply, c(list(X = X, FUN = fun), a)) }, ns)
  if (exists("parSapply", ns)) { unlockBinding("parSapply", ns); assign("parSapply", function(cl, X, fun, ...) { a <- list(...); a[["chunk.size"]] <- NULL; do.call(base::sapply, c(list(X = X, FUN = fun), a)) }, ns) }
  for (fn in c("clusterExport","clusterEvalQ","clusterCall","clusterApply","clusterApplyLB","stopCluster","clusterSetRNGStream")) if (exists(fn, ns)) { unlockBinding(fn, ns); assign(fn, function(...) invisible(NULL), ns) }
})
library(seminr)

# Hand-rolled z0-adjusted percentile BC (U6-T3) - reused verbatim from the lavaan-verified text
# (src/lib/stats/plsBcCi.ts); seminr has no built-in bca.simple, so bc_ci() runs here against
# bo$boot_paths' raw draws (a [from, to, boot_index] 3D array).

norm_inter <- function(t, alpha) {
  t <- t[is.finite(t)]; R <- length(t)
  rk <- (R + 1) * alpha
  k <- trunc(rk)
  tstar <- sort(t)
  out <- numeric(length(k))
  for (j in seq_along(k)) {
    if (k[j] == rk[j])      out[j] <- tstar[k[j]]
    else if (k[j] == 0)     out[j] <- tstar[1]
    else if (k[j] == R)     out[j] <- tstar[R]
    else {
      temp1 <- qnorm(alpha[j]); temp2 <- qnorm(k[j] / (R + 1)); temp3 <- qnorm((k[j] + 1) / (R + 1))
      out[j] <- tstar[k[j]] + (temp1 - temp2) / (temp3 - temp2) * (tstar[k[j] + 1] - tstar[k[j]])
    }
  }
  out
}
bc_ci <- function(draws, t0, level = 0.95) {
  draws <- draws[is.finite(draws)]
  zalpha <- qnorm((1 + c(-level, level)) / 2)
  w <- qnorm(sum(draws < t0) / length(draws))
  norm_inter(draws, pnorm(2 * w + zalpha))
}


# Measurement model (reflective = mode_A; formative = mode_B)
mm <- constructs(
  composite("visual", c("x1", "x2", "x3"), weights = mode_A),
  composite("textual", c("x4", "x5", "x6"), weights = mode_A),
  composite("speed", c("x7", "x8", "x9"), weights = mode_A)
)

# Structural model (paths by construct name)
sm <- relationships(
  paths(from = "visual", to = "textual"),
  paths(from = "textual", to = "speed"),
  paths(from = "visual", to = "speed")
)

# Estimate + bootstrap (percentile CI; serial cores under the shim)
gc()
pls <- estimate_pls(data = d, measurement_model = mm, structural_model = sm)
s <- summary(pls)
set.seed(20260620)
bo <- bootstrap_model(seminr_model = pls, nboot = 5000, cores = 1)
sb <- summary(bo)
gc()

# The DRAWN construct names only - excludes seminr's derived interaction construct (no meaningful
# alpha/AVE/HTMT/outer rows; its structural row still flows through the path loop below).
construct_names <- c("visual", "textual", "speed")
formative_names <- c()

# ---- Table 1: Measurement model (construct alpha/rhoA/CR/AVE + item mean/sd/loading-or-weight/t/p) ----
# Raw seminr reliability order is alpha/rhoC/AVE/rhoA - reordered here to the display tuple.
rel <- s$reliability[, c("alpha", "rhoA", "rhoC", "AVE"), drop = FALSE]
if (length(formative_names)) rel[rownames(rel) %in% formative_names, "AVE"] <- NA
cat("\n--- Table 1: Measurement model ---\n")
for (nm in construct_names) {
  is_form <- nm %in% formative_names
  cat(sprintf("%s: alpha=%.3f rhoA=%.3f CR=%.3f AVE=%s\n",
              nm, rel[nm, "alpha"], rel[nm, "rhoA"], rel[nm, "rhoC"],
              if (is_form) "NA" else sprintf("%.3f", rel[nm, "AVE"])))
  items_nm <- pls$mmMatrix[pls$mmMatrix[, "construct"] == nm, "measurement"]
  for (it in items_nm) {
    key <- paste0(it, "  ->  ", nm)
    m <- mean(d[[it]], na.rm = TRUE); sdv <- sd(d[[it]], na.rm = TRUE)
    if (is_form) {
      w <- as.numeric(sb$bootstrapped_weights[key, "Original Est."])
      tval <- as.numeric(sb$bootstrapped_weights[key, "T Stat."])
      cat(sprintf("  %s: weight=%.3f t=%.3f p=%.4f mean=%.3f sd=%.3f\n",
                  it, w, tval, 2 * pnorm(-abs(tval)), m, sdv))
    } else {
      l <- as.numeric(sb$bootstrapped_loadings[key, "Original Est."])
      tval <- as.numeric(sb$bootstrapped_loadings[key, "T Stat."])
      cat(sprintf("  %s: loading=%.3f t=%.3f p=%.4f mean=%.3f sd=%.3f\n",
                  it, l, tval, 2 * pnorm(-abs(tval)), m, sdv))
    }
  }
}

# ---- Table 2: HTMT ----
cat("\n--- Table 2: HTMT ---\n")
print(round(s$validity$htmt[construct_names, construct_names, drop = FALSE], 3))

# ---- Table 3: Structural paths (β + t/p + dual 95% CI: percentile & hand-rolled BC) ----
bp <- sb$bootstrapped_paths
fsq <- s$fSquare
path_from_all <- c("visual", "textual", "visual")
path_to_all   <- c("textual", "speed", "speed")
struct_beta <- numeric(length(path_from_all)); struct_t <- numeric(length(path_from_all))
struct_p <- numeric(length(path_from_all))
struct_perc_lo <- numeric(length(path_from_all)); struct_perc_hi <- numeric(length(path_from_all))
struct_bc_lo <- numeric(length(path_from_all)); struct_bc_hi <- numeric(length(path_from_all))
for (e in seq_along(path_from_all)) {
  fr <- path_from_all[e]; to <- path_to_all[e]
  key <- paste0(fr, "  ->  ", to)
  beta_e <- as.numeric(bp[key, "Original Est."])
  tval_e <- as.numeric(bp[key, "T Stat."])
  bcc <- bc_ci(bo$boot_paths[fr, to, ], beta_e)
  struct_beta[e] <- beta_e; struct_t[e] <- tval_e; struct_p[e] <- 2 * pnorm(-abs(tval_e))
  struct_perc_lo[e] <- as.numeric(bp[key, "2.5% CI"]); struct_perc_hi[e] <- as.numeric(bp[key, "97.5% CI"])
  struct_bc_lo[e] <- as.numeric(bcc[1]); struct_bc_hi[e] <- as.numeric(bcc[2])
}
struct_tab <- data.frame(
  h = paste0("H", seq_along(path_from_all)),
  path = paste(path_from_all, "->", path_to_all),
  beta = struct_beta, t = struct_t, pvalue = struct_p,
  perc.lower = struct_perc_lo, perc.upper = struct_perc_hi,
  bc.lower = struct_bc_lo, bc.upper = struct_bc_hi
)
cat("\n--- Table 3: Structural paths ---\n")
print(struct_tab)

# ---- Table 4: Structural quality (R² / R²adj / Q²_predict) ----
paths_tbl <- s$paths
endo <- colnames(paths_tbl)
set.seed(20260620)
q2_pred <- tryCatch({
  pp <- predict_pls(pls)
  sp <- summary(pp)
  1 - sp$PLS_out_of_sample["RMSE", ]^2 / sp$LM_out_of_sample["RMSE", ]^2
}, error = function(e) NULL)
quality_tab <- data.frame(
  construct = endo,
  r2 = as.numeric(paths_tbl["R^2", endo]), r2adj = as.numeric(paths_tbl["AdjR^2", endo]),
  q2 = sapply(endo, function(nm) {
    if (is.null(q2_pred)) return(NA)
    its <- pls$mmMatrix[pls$mmMatrix[, "construct"] == nm, "measurement"]
    its <- its[its %in% names(q2_pred)]
    if (length(its)) mean(q2_pred[its]) else NA
  })
)
cat("\n--- Table 4: Structural quality (R^2 / AdjR^2 / Q^2_predict) ---\n")
print(round(quality_tab[, c("r2", "r2adj", "q2")], 4))

# ---- Table 5: Indirect effects (specific_effect_significance over each mediated triple) ----
# Interaction edges are skipped: the interaction construct is not a dimname of adj and never
# participates in a mediation chain (no incoming paths) - matches plsSem.ts's R block exactly.
cat("\n--- Table 5: Indirect effects ---\n")
k_cn <- length(construct_names)
adj <- matrix(FALSE, k_cn, k_cn, dimnames = list(construct_names, construct_names))
adj["visual", "textual"] <- TRUE
adj["textual", "speed"] <- TRUE
adj["visual", "speed"] <- TRUE
for (a in construct_names) for (z in construct_names) if (a != z) {
  for (m in construct_names[adj[a, ] & adj[, z]]) {
    sig <- tryCatch(specific_effect_significance(bo, from = a, through = m, to = z, alpha = 0.05),
                    error = function(e) NULL)
    if (!is.null(sig)) { cat(sprintf("  %s -> %s -> %s: ", a, m, z)); print(round(sig, 4)) }
  }
}

# Figure: path diagram — semPaths stand-in (the app exports the annotated SVG via html-to-image)
cat("\n--- Figure: PLS path diagram (semPaths reproducible stand-in) ---\n")
tryCatch(print(plot(pls)), error = function(e) cat("(diagram skipped:", conditionMessage(e), ")\n"))