# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("modelsummary", "ggplot2"))
library(modelsummary)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$gender <- factor(d$gender)

# === 01 · Summary statistics ===
summ <- data.frame("score" = d[["score"]], "anxiety" = d[["anxiety"]], grp = d[["gender"]], check.names = FALSE)
print(datasummary_skim(summ, type = "numeric", by = "grp"))
print(ggplot(d, aes(score)) + geom_histogram(bins = 12))
print(ggplot(d, aes(anxiety)) + geom_histogram(bins = 12))