# Native R 4.6.0 ground truth for econometrics sub-slice 2 fixtures.
# Reference values the WebR runners must reproduce (cross-check via vitest later).
options(width = 200)
suppressMessages({ library(plm); library(sandwich); library(lmtest); library(AER); library(rdrobust); library(MatchIt) })
P <- read.csv("/Users/benjie/Documents/Telos/tests/e2e/fixtures/panel.csv")
C <- read.csv("/Users/benjie/Documents/Telos/tests/e2e/fixtures/causal.csv")
line <- function(s) cat("\n========== ", s, " ==========\n", sep = "")

pdat <- pdata.frame(P, index = c("firm", "year"))

line("FIXED EFFECTS (within)")
fe <- plm(roa ~ leverage + rd_spend + size, data = pdat, model = "within")
fe_cl <- vcovHC(fe, method = "arellano", type = "HC1", cluster = "group")
print(coeftest(fe, vcov = fe_cl))
cat("within R2 =", summary(fe)$r.squared["rsq"], " adjR2 =", summary(fe)$r.squared["adjrsq"], "\n")
cat("F =", summary(fe)$fstatistic$statistic, " df =", summary(fe)$fstatistic$parameter, " p =", summary(fe)$fstatistic$p.value, "\n")
cat("N obs =", nobs(fe), " N entities =", pdim(fe)$nT$n, " (clustered CI 95%):\n")
print(coefci(fe, vcov = fe_cl, level = 0.95))

line("RANDOM EFFECTS (swamy-arora)")
re <- plm(roa ~ leverage + rd_spend + size, data = pdat, model = "random")
re_cl <- vcovHC(re, method = "arellano", type = "HC1", cluster = "group")
print(coeftest(re, vcov = re_cl))
cat("R2 =", summary(re)$r.squared["rsq"], " adjR2 =", summary(re)$r.squared["adjrsq"], "\n")
cat("N obs =", nobs(re), " N entities =", pdim(re)$nT$n, "\n")

line("HAUSMAN")
h <- phtest(fe, re)
cat("chisq =", h$statistic, " df =", h$parameter, " p =", h$p.value, "\n")
cat("FE coefs:\n"); print(coef(fe))
cat("RE coefs (slopes):\n"); print(coef(re)[names(coef(fe))])

line("DiD (lm + clustered-by-firm SE)")
did <- lm(roa ~ treated * post, data = P)
did_cl <- vcovCL(did, cluster = ~firm)
print(coeftest(did, vcov = did_cl))
print(coefci(did, vcov = did_cl, level = 0.95))

line("IV / 2SLS")
fs <- lm(educ ~ educ_iv + exper, data = C)
cat("First stage coef(educ_iv):\n"); print(summary(fs)$coefficients["educ_iv", ])
fs0 <- lm(educ ~ exper, data = C)
cat("Partial F (instrument):\n"); print(anova(fs0, fs))
iv <- ivreg(wage ~ educ + exper | educ_iv + exper, data = C)
print(summary(iv, vcov = sandwich, diagnostics = TRUE))

line("RDD (rdrobust, cutoff 50)")
rd <- rdrobust(C$score, C$running_var, c = 50)
cat("coef:\n"); print(rd$coef); cat("se:\n"); print(rd$se); cat("z:\n"); print(rd$z)
cat("pv:\n"); print(rd$pv); cat("ci:\n"); print(rd$ci); cat("bws:\n"); print(rd$bws)
cat("Nh (left/right) =", rd$N_h, "\n")

line("PSM (MatchIt nearest 1:1)")
m <- matchit(enroll ~ exper + age + ability, data = C, method = "nearest", ratio = 1)
s <- summary(m)
cat("Balance ALL (pre):\n"); print(round(s$sum.all[, c("Means Treated", "Means Control", "Std. Mean Diff.", "Var. Ratio")], 4))
cat("Balance MATCHED (post):\n"); print(round(s$sum.matched[, c("Std. Mean Diff.", "Var. Ratio")], 4))
md <- match.data(m)
att <- lm(health ~ enroll, data = md, weights = weights)
att_v <- vcovCL(att, cluster = ~subclass)
cat("ATT:\n"); print(coeftest(att, vcov = att_v))
print(coefci(att, vcov = att_v, level = 0.95))
cat("matched n =", nrow(md), "\n")
