# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("afex", "effectsize", "emmeans", "ggplot2"))
library(afex)
library(effectsize)
library(emmeans)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$group <- factor(d$group)
d$gender <- factor(d$gender)

# === 01 · Factorial ANOVA ===
fad <- data.frame(.sid = factor(seq_along(d[["outcome"]])), y = d[["outcome"]], f1 = factor(d[["group"]]), f2 = factor(d[["gender"]]))
m <- afex::aov_car(y ~ f1 * f2 + Error(.sid), data = fad, anova_table = list(es = "pes"))
print(m$anova_table)
print(effectsize::eta_squared(m$lm, partial = TRUE))
print(summary(pairs(emmeans::emmeans(m, ~ f1), adjust = "tukey"), infer = TRUE))
print(summary(pairs(emmeans::emmeans(m, ~ f2), adjust = "tukey"), infer = TRUE))
agg <- aggregate(list(m = fad$y), by = list(a = fad$f1, b = fad$f2), FUN = mean)
print(ggplot(agg, aes(a, m, group = b, colour = b)) + geom_line() + geom_point() + labs(x = NULL, y = NULL, colour = "gender"))