# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("nortest", "ggplot2"))
library(nortest)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)

# === 01 · Distribution & normality ===
xv <- na.omit(d[["exam_score"]]); nv <- length(xv)
if (nv >= 3 && nv <= 5000) print(shapiro.test(xv)) else cat("Shapiro-Wilk: n outside [3, 5000]\n")
if (nv >= 5) print(nortest::lillie.test(xv)) else cat("Lilliefors: n too small (need n >= 5)\n")
print(ggplot(d, aes(exam_score)) + geom_histogram(bins = max(5L, min(30L, ceiling(log2(length(na.omit(d[["exam_score"]]))) + 1)))) + labs(x = "exam_score", y = "Count"))
print(ggplot(d, aes(sample = exam_score)) + stat_qq() + stat_qq_line() + labs(x = "Theoretical quantiles", y = "Sample quantiles"))
xv <- na.omit(d[["absences"]]); nv <- length(xv)
if (nv >= 3 && nv <= 5000) print(shapiro.test(xv)) else cat("Shapiro-Wilk: n outside [3, 5000]\n")
if (nv >= 5) print(nortest::lillie.test(xv)) else cat("Lilliefors: n too small (need n >= 5)\n")
print(ggplot(d, aes(absences)) + geom_histogram(bins = max(5L, min(30L, ceiling(log2(length(na.omit(d[["absences"]]))) + 1)))) + labs(x = "absences", y = "Count"))
print(ggplot(d, aes(sample = absences)) + stat_qq() + stat_qq_line() + labs(x = "Theoretical quantiles", y = "Sample quantiles"))