# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("nortest", "ggplot2"))
library(nortest)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)

# === 01 · Distribution & normality ===
xv <- na.omit(d[["score"]]); nv <- length(xv)
if (nv >= 3 && nv <= 5000) print(shapiro.test(xv)) else cat("Shapiro-Wilk: n outside [3, 5000]\n")
if (nv >= 5) print(nortest::lillie.test(xv)) else cat("Lilliefors: n too small (need n >= 5)\n")
print(ggplot(d, aes(score)) + geom_histogram(bins = max(5L, min(30L, ceiling(log2(length(na.omit(d[["score"]]))) + 1)))) + labs(x = "score", y = "Count"))
print(ggplot(d, aes(sample = score)) + stat_qq() + stat_qq_line() + labs(x = "Theoretical quantiles", y = "Sample quantiles"))
xv <- na.omit(d[["anxiety"]]); nv <- length(xv)
if (nv >= 3 && nv <= 5000) print(shapiro.test(xv)) else cat("Shapiro-Wilk: n outside [3, 5000]\n")
if (nv >= 5) print(nortest::lillie.test(xv)) else cat("Lilliefors: n too small (need n >= 5)\n")
print(ggplot(d, aes(anxiety)) + geom_histogram(bins = max(5L, min(30L, ceiling(log2(length(na.omit(d[["anxiety"]]))) + 1)))) + labs(x = "anxiety", y = "Count"))
print(ggplot(d, aes(sample = anxiety)) + stat_qq() + stat_qq_line() + labs(x = "Theoretical quantiles", y = "Sample quantiles"))