# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("ivreg", "sandwich", "lmtest", "ggplot2"))
library(ivreg)
library(sandwich)
library(lmtest)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)

# === 01 · Instrumental variables (IV / 2SLS) ===
iv  <- ivreg::ivreg(wage ~ educ + exper | educ_iv + exper, data = d)
ols <- lm(wage ~ educ + exper, data = d)
V  <- sandwich::vcovHC(iv, type = 'HC1')
Vo <- sandwich::vcovHC(ols, type = 'HC1')
print(lmtest::coeftest(iv, vcov. = V))
print(lmtest::coefci(iv, vcov. = V, level = 0.95))
print(lmtest::coeftest(ols, vcov. = Vo))
# First stage (instrument strength) — partial F = (t-stat)^2
fs <- lm(educ ~ educ_iv + exper, data = d)
print(summary(fs)$coefficients)
# Diagnostics: weak instruments F, Wu-Hausman, Sargan (when over-identified)
print(summary(iv, diagnostics = TRUE))
# Figure — OLS vs 2SLS coefficient plot (endogenous regressors)
terms <- c("educ")
ivc <- lmtest::coefci(iv, vcov. = V, level = 0.95); olc <- lmtest::coefci(ols, vcov. = Vo, level = 0.95)
pdat <- rbind(
  data.frame(term = terms, model = "OLS", est = unname(coef(ols)[terms]), lo = olc[terms, 1], hi = olc[terms, 2]),
  data.frame(term = terms, model = "2SLS", est = unname(coef(iv)[terms]), lo = ivc[terms, 1], hi = ivc[terms, 2]))
pdat$term <- factor(pdat$term, levels = rev(terms))
print(ggplot(pdat, aes(x = est, y = term, colour = model)) +
  geom_vline(xintercept = 0, colour = "#9cc2ec", linetype = "dashed") +
  geom_pointrange(aes(xmin = lo, xmax = hi), position = position_dodge(width = 0.4)) +
  scale_colour_manual(values = c(OLS = "#0c447c", "2SLS" = "#c8781e")) +
  labs(x = "Estimate (endogenous regressor)", y = NULL, colour = NULL))