# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("psych", "effectsize", "ggplot2"))
library(psych)
library(effectsize)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)

# === 01 · Paired t-test ===
print(psych::describe(data.frame(a = d[["pre"]], b = d[["post"]])))
res <- t.test(d[["pre"]], d[["post"]], paired = TRUE, conf.level = 0.95, alternative = "two.sided")
print(res)
effectsize::cohens_d(d[["pre"]], d[["post"]], paired = TRUE)
pl <- data.frame(case = rep(seq_along(d[["pre"]]), 2),
  cond = factor(rep(c("pre", "post"), each = length(d[["pre"]])), levels = c("pre", "post")),
  value = c(d[["pre"]], d[["post"]]))
print(ggplot(pl, aes(cond, value, group = case)) +
  geom_line(colour = "#9cc2ec") + geom_point(colour = "#0c447c") + labs(x = NULL, y = NULL))