# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("rstatix", "ggplot2"))
library(rstatix)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$group <- factor(d$group)

# === 01 · Kruskal-Wallis ===
kw <- kruskal.test(d[["outcome"]] ~ factor(d[["group"]]))
print(kw)
nn <- length(d[["outcome"]]); h <- unname(kw$statistic); eps2 <- h * (nn + 1) / (nn^2 - 1)
cat("epsilon-squared:", eps2, "\n")
print(rstatix::dunn_test(data.frame(y = d[["outcome"]], g = factor(d[["group"]])), y ~ g, p.adjust.method = "holm"))
print(ggplot(data.frame(group = factor(d[["group"]]), score = d[["outcome"]]), aes(group, score)) +
  geom_boxplot(fill = "#9cc2ec", colour = "#0c447c") + labs(x = NULL, y = NULL))