# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("effectsize", "ggplot2"))
library(effectsize)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)

# === 01 · One-sample t-test ===
res <- t.test(d[["pretest_score"]], mu = 50, conf.level = 0.95, alternative = "two.sided")
print(res)
effectsize::cohens_d(d[["pretest_score"]], mu = 50)
if (length(d[["pretest_score"]]) >= 3 && length(d[["pretest_score"]]) <= 5000) print(shapiro.test(d[["pretest_score"]]))
print(ggplot(data.frame(x = d[["pretest_score"]]), aes(x)) +
  geom_histogram(bins = nclass.Sturges(d[["pretest_score"]]), fill = "#9cc2ec", colour = "#0c447c") +
  geom_vline(xintercept = 50, colour = "#0c447c", linetype = "dashed") + labs(x = NULL, y = NULL))