# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("ggplot2"))
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)

# === 01 · Kendall's tau ===
ct <- suppressWarnings(cor.test(d[["motivation_1"]], d[["motivation_2"]], method = "kendall", exact = FALSE, alternative = "two.sided"))
print(ct)
print(ggplot(d, aes(motivation_1, motivation_2)) + geom_point())