# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("modelsummary", "ggplot2", "MASS", "performance"))
library(modelsummary)
library(ggplot2)
library(MASS)
library(performance)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$group <- factor(d$group)

# === 01 · Poisson / negative binomial ===
m <- glm(complaints ~ age + group + offset(log(months_observed)), family = poisson, data = d)
modelsummary(list("Odds ratio" = m), exponentiate = TRUE, statistic = "conf.int", stars = FALSE, fmt = 3, gof_map = c("nobs", "r.squared", "adj.r.squared", "aic", "bic", "logLik", "rmse"), output = "markdown")
# Poisson dispersion ratio (overdispersion)
print(performance::check_overdispersion(m)$dispersion_ratio)
# Figure — fitted vs. Pearson residuals
pd <- data.frame(fitted = fitted(m), resid = residuals(m, type = "pearson"))
print(ggplot(pd, aes(fitted, resid)) +
  geom_hline(yintercept = 0, colour = "#9cc2ec", linetype = "dashed") +
  geom_point(colour = "#0c447c") + labs(x = "Fitted values", y = "Pearson residuals"))