# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("ggplot2"))
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$method <- factor(d$method)
d$passed <- factor(d$passed)

# === 01 · Chi-square independence ===
sub <- d[!is.na(d[["method"]]) & trimws(d[["method"]]) != "" & !is.na(d[["passed"]]) & trimws(d[["passed"]]) != "", ]
tab <- table(sub[["method"]], sub[["passed"]])
g <- suppressWarnings(chisq.test(tab, correct = TRUE))
print(g)
print(g$expected)
print(prop.table(tab, 1) * 100)
print(prop.table(tab, 2) * 100)
cat("Cramer's V:", sqrt(unname(suppressWarnings(chisq.test(tab, correct = FALSE))$statistic) / (sum(tab) * (min(dim(tab)) - 1))), "\n")
print(ggplot(sub, aes(method, fill = passed)) + geom_bar(position = "dodge"))