# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("plm", "lmtest", "ggplot2"))
library(plm)
library(lmtest)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d[["province"]] <- factor(d[["province"]])

# === 01 · Fixed effects ===
pdat <- plm::pdata.frame(d, index = c("province", "year"))
fit <- plm::plm(growth ~ investment + education_spend + urbanization, data = pdat, model = 'within', effect = 'individual')
V <- plm::vcovHC(fit, method = 'arellano', type = 'HC1', cluster = 'group')
print(lmtest::coeftest(fit, vcov. = V))
print(lmtest::coefci(fit, vcov. = V, level = 0.95))
print(summary(fit))
# Between/overall R2 (Stata xtreg convention, R1 gap-fix) - within already equals summary(fit)$r.squared
xb <- as.numeric(as.matrix(d[, c("investment", "education_spend", "urbanization"), drop = FALSE]) %*% coef(fit)[c("investment", "education_spend", "urbanization")])
agg <- aggregate(cbind(yy, xbxb) ~ idid, data.frame(idid = d$province, yy = d$growth, xbxb = xb), mean)
cat("Between R2:", cor(agg$yy, agg$xbxb)^2, "\n")
cat("Overall R2:", cor(d$growth, xb)^2, "\n")
# Poolability F-test (within vs pooled OLS)
print(plm::pFtest(fit, plm::plm(growth ~ investment + education_spend + urbanization, data = pdat, model = 'pooling')))
# Figure - within-estimate coefficient plot (95% CI)
ci <- lmtest::coefci(fit, vcov. = V, level = 0.95); est <- coef(fit); labs <- names(est)
pf <- data.frame(term = factor(labs, levels = rev(labs)), b = unname(est), lo = ci[, 1], hi = ci[, 2])
print(ggplot(pf, aes(x = b, y = term)) +
  geom_vline(xintercept = 0, colour = "#9cc2ec", linetype = "dashed") +
  geom_pointrange(aes(xmin = lo, xmax = hi), colour = "#0c447c") +
  labs(x = "Within estimate (95% CI)", y = NULL))