# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("plm", "lmtest", "ggplot2"))
library(plm)
library(lmtest)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$firm <- factor(d$firm)

# === 01 · Fixed effects ===
pdat <- plm::pdata.frame(d, index = c("firm", "year"))
fit <- plm::plm(roa ~ leverage + rd_spend + size, data = pdat, model = 'within', effect = 'individual')
V <- plm::vcovHC(fit, method = 'arellano', type = 'HC1', cluster = 'group')
print(lmtest::coeftest(fit, vcov. = V))
print(lmtest::coefci(fit, vcov. = V, level = 0.95))
print(summary(fit))
# Poolability F-test (within vs pooled OLS)
print(plm::pFtest(fit, plm::plm(roa ~ leverage + rd_spend + size, data = pdat, model = 'pooling')))
# Figure — within-estimate coefficient plot (95% CI)
ci <- lmtest::coefci(fit, vcov. = V, level = 0.95); est <- coef(fit); labs <- names(est)
pf <- data.frame(term = factor(labs, levels = rev(labs)), b = unname(est), lo = ci[, 1], hi = ci[, 2])
print(ggplot(pf, aes(x = b, y = term)) +
  geom_vline(xintercept = 0, colour = "#9cc2ec", linetype = "dashed") +
  geom_pointrange(aes(xmin = lo, xmax = hi), colour = "#0c447c") +
  labs(x = "Within estimate (95% CI)", y = NULL))