# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("afex", "emmeans", "ggplot2"))
library(afex)
library(emmeans)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$subject_id <- factor(d$subject_id)
d$group <- factor(d$group)

# === 01 · Mixed ANOVA ===
conds <- c("score_t1", "score_t2", "score_t3")
nrw <- length(d[["score_t1"]])
long <- data.frame(sid = factor(rep(d[["subject_id"]], length(conds))),
  grp = factor(rep(d[["group"]], length(conds))),
  condition = factor(rep(conds, each = nrw), levels = conds),
  score = c(d[["score_t1"]], d[["score_t2"]], d[["score_t3"]]))
m <- afex::aov_ez(id = "sid", dv = "score", data = long, between = "grp", within = "condition",
  anova_table = list(es = "pes", correction = "GG"))
print(m$anova_table)
print(summary(m$Anova, multivariate = FALSE))
print(summary(pairs(emmeans::emmeans(m, ~ condition), adjust = "bonferroni"), infer = TRUE))
mat <- matrix(c(d[["score_t1"]], d[["score_t2"]], d[["score_t3"]]), ncol = length(conds)); gv <- factor(d[["group"]])
agg <- do.call(rbind, lapply(levels(gv), function(l) {
  sub <- mat[gv == l, , drop = FALSE]; mm <- colMeans(sub); se <- apply(sub, 2, sd) / sqrt(nrow(sub))
  tq <- qt(0.975, nrow(sub) - 1)
  data.frame(grp = l, cond = factor(conds, levels = conds), m = mm, lo = mm - tq * se, hi = mm + tq * se) }))
print(ggplot(agg, aes(cond, m, group = grp, colour = grp)) + geom_line() +
  geom_pointrange(aes(ymin = lo, ymax = hi)) + labs(x = NULL, y = NULL, colour = NULL))