# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("modelsummary", "ggplot2"))
library(modelsummary)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d[["teaching_method"]] <- factor(d[["teaching_method"]])

# === 01 · Frequencies & cross-tabs ===
sub <- d[!is.na(d[["teaching_method"]]) & trimws(d[["teaching_method"]]) != "", ]
sub[["teaching_method"]] <- factor(sub[["teaching_method"]])
print(datasummary(teaching_method ~ N + Percent(), data = sub))
print(ggplot(sub, aes(teaching_method)) + geom_bar())