# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("modelsummary", "ggplot2"))
library(modelsummary)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$group <- factor(d$group)

# === 01 · Frequencies & cross-tabs ===
sub <- d[!is.na(d[["group"]]) & trimws(d[["group"]]) != "", ]
sub[["group"]] <- factor(sub[["group"]])
print(datasummary(group ~ N + Percent(), data = sub))
print(ggplot(sub, aes(group)) + geom_bar())