# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("MatchIt", "sandwich", "lmtest", "ggplot2"))
library(MatchIt)
library(sandwich)
library(lmtest)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)

# === 01 · Propensity score matching ===
# code treatment to 0/1 by the positive level
md0 <- d; md0$treat <- ifelse(as.character(d$enroll) == "1", 1, 0)
m <- MatchIt::matchit(treat ~ exper + wage + ability, data = md0, method = 'nearest', ratio = 1)
print(summary(m))  # covariate balance (before / after)
# ATT via weighted lm on matched data with subclass-clustered SE
md <- MatchIt::match.data(m)
att <- lm(health ~ treat, data = md, weights = md$weights)
V <- sandwich::vcovCL(att, cluster = md$subclass)
print(lmtest::coeftest(att, vcov. = V))
print(lmtest::coefci(att, vcov. = V, level = 0.95))
# Figure — love plot (|SMD| per covariate, unmatched vs matched, ref line at 0.1)
sm <- summary(m); covn <- c("exper", "wage", "ability")
lp <- data.frame(cov = rep(covn, 2),
  smd = abs(c(sm$sum.all[covn, "Std. Mean Diff."], sm$sum.matched[covn, "Std. Mean Diff."])),
  sample = factor(rep(c("Unmatched", "Matched"), each = length(covn)), levels = c("Unmatched", "Matched")))
lp$cov <- factor(lp$cov, levels = rev(covn))
print(ggplot(lp, aes(x = smd, y = cov, colour = sample)) +
  geom_vline(xintercept = 0.1, colour = "#9cc2ec", linetype = "dashed") +
  geom_point(size = 3) +
  scale_colour_manual(values = c(Unmatched = "#c8781e", Matched = "#0c447c")) +
  labs(x = "|Standardized mean difference|", y = NULL, colour = NULL))