# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("tseries", "ggplot2"))
library(tseries)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$month <- factor(d$month)

# === 01 · Stationarity tests (ADF, KPSS) ===
dd_ord <- d[order(d$month), ]
x_ts <- ts(dd_ord$sales, frequency = 1)
print(tseries::adf.test(x_ts))
print(tseries::kpss.test(x_ts))
print(tseries::pp.test(x_ts))
# Figure 1 — level + first-difference series
nn <- length(x_ts); idx <- seq_len(nn); dx <- c(NA_real_, diff(as.numeric(x_ts)))
sdf <- rbind(data.frame(panel = "Level", t = idx, y = as.numeric(x_ts)),
             data.frame(panel = "First diff.", t = idx, y = dx))
sdf$panel <- factor(sdf$panel, levels = c("Level", "First diff."))
print(ggplot(sdf, aes(t, y)) + geom_line(colour = "#0c447c") +
  facet_wrap(~panel, scales = "free_y", ncol = 1) + labs(x = "month", y = NULL) + theme_minimal())
# Figure 2 — ACF + PACF
ci <- qnorm(0.975) / sqrt(nn); ac <- acf(x_ts, plot = FALSE); pac <- pacf(x_ts, plot = FALSE)
adf2 <- rbind(data.frame(panel = "ACF", lag = as.numeric(ac$lag[-1]), value = as.numeric(ac$acf[-1])),
              data.frame(panel = "PACF", lag = as.numeric(pac$lag), value = as.numeric(pac$acf)))
adf2$panel <- factor(adf2$panel, levels = c("ACF", "PACF"))
print(ggplot(adf2, aes(x = lag, y = value)) +
  geom_hline(yintercept = c(ci, -ci), linetype = "dashed", colour = "#9cc2ec") +
  geom_hline(yintercept = 0, colour = "grey50") +
  geom_segment(aes(xend = lag, yend = 0), colour = "#0c447c") +
  facet_wrap(~panel, ncol = 1, scales = "free_y") + labs(x = "Lag", y = NULL) + theme_minimal())