# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("effectsize", "ggplot2"))
library(effectsize)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$method <- factor(d$method)

# === 01 · Chi-square goodness-of-fit ===
sub <- d[!is.na(d[["method"]]) & trimws(d[["method"]]) != "", ]
tab <- table(sub[["method"]])
pr <- c(0.5, 0.3, 0.2); pr <- pr / sum(pr)
g <- suppressWarnings(chisq.test(tab, p = pr))
w <- as.numeric(effectsize::cohens_w(tab, p = pr)$Cohens_w)
print(g)
print(g$stdres)
cat("Cohen's w:", w, "\n")
k <- length(tab)
gof_d <- data.frame(category = factor(rep(names(tab), 2), levels = names(tab)),
  kind = factor(rep(c('Observed', 'Expected'), each = k), levels = c('Observed', 'Expected')),
  count = c(as.numeric(tab), as.numeric(g$expected)))
print(ggplot(gof_d, aes(category, count, fill = kind)) + geom_col(position = "dodge"))