# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("effectsize", "emmeans", "ggplot2"))
library(effectsize)
library(emmeans)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$group <- factor(d$group)

# === 01 · One-way ANOVA + post-hoc ===
owa <- data.frame(y = d[["outcome"]], g = factor(d[["group"]]))
m <- aov(d[["outcome"]] ~ factor(d[["group"]]), data = owa)
print(summary(m))
print(effectsize::eta_squared(m, partial = FALSE))
m2 <- aov(y ~ g, data = owa)  # named-factor refit so emmeans can reference the grouping term
print(summary(pairs(emmeans::emmeans(m2, ~ g), adjust = "tukey"), infer = TRUE, level = 0.95))
gf <- factor(d[["group"]]); agg <- data.frame(g = levels(gf), m = as.numeric(tapply(d[["outcome"]], gf, mean)))
nn <- as.numeric(tapply(d[["outcome"]], gf, length)); sdv <- as.numeric(tapply(d[["outcome"]], gf, sd))
se <- sdv / sqrt(nn); tq <- qt(1 - (1 - 0.95) / 2, nn - 1)
agg$lo <- agg$m - tq * se; agg$hi <- agg$m + tq * se
print(ggplot(agg, aes(g, m)) + geom_pointrange(aes(ymin = lo, ymax = hi), colour = "#0c447c") + labs(x = NULL, y = NULL))