# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("modelsummary", "effectsize", "emmeans", "ggplot2"))
library(modelsummary)
library(effectsize)
library(emmeans)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d[["teaching_method"]] <- factor(d[["teaching_method"]])

# === 01 · One-way ANOVA + post-hoc ===
owa <- data.frame(y = d[["exam_score"]], g = factor(d[["teaching_method"]]))
print(datasummary_balance(~g, data = owa, dinm = FALSE))  # Table 1 (Arel-Bundock datasummary)
m <- aov(d[["exam_score"]] ~ factor(d[["teaching_method"]]), data = owa)
print(summary(m))
print(effectsize::eta_squared(m, partial = FALSE))
m2 <- aov(y ~ g, data = owa)  # named-factor refit so emmeans can reference the grouping term
print(summary(pairs(emmeans::emmeans(m2, ~ g), adjust = "tukey"), infer = TRUE, level = 0.99))
gf <- factor(d[["teaching_method"]]); agg <- data.frame(g = levels(gf), m = as.numeric(tapply(d[["exam_score"]], gf, mean)))
nn <- as.numeric(tapply(d[["exam_score"]], gf, length)); sdv <- as.numeric(tapply(d[["exam_score"]], gf, sd))
se <- sdv / sqrt(nn); tq <- qt(1 - (1 - 0.99) / 2, nn - 1)
agg$lo <- agg$m - tq * se; agg$hi <- agg$m + tq * se
print(ggplot(agg, aes(g, m)) + geom_pointrange(aes(ymin = lo, ymax = hi), colour = "#0c447c") + labs(x = NULL, y = NULL))