# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("modelsummary", "rstatix", "ggplot2"))
library(modelsummary)
library(rstatix)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d[["teaching_method"]] <- factor(d[["teaching_method"]])

# === 01 · Welch's ANOVA ===
wdf <- data.frame(y = d[["exam_score"]], g = factor(d[["teaching_method"]]))
print(datasummary_balance(~g, data = wdf, dinm = FALSE))  # Table 1 (Arel-Bundock datasummary)
res <- oneway.test(d[["exam_score"]] ~ factor(d[["teaching_method"]]), var.equal = FALSE)
print(res)
print(rstatix::games_howell_test(data.frame(y = d[["exam_score"]], g = factor(d[["teaching_method"]])), y ~ g))
gf <- factor(d[["teaching_method"]]); agg <- data.frame(g = levels(gf), m = as.numeric(tapply(d[["exam_score"]], gf, mean)))
nn <- as.numeric(tapply(d[["exam_score"]], gf, length)); sdv <- as.numeric(tapply(d[["exam_score"]], gf, sd))
se <- sdv / sqrt(nn); tq <- qt(0.975, nn - 1); agg$lo <- agg$m - tq * se; agg$hi <- agg$m + tq * se
print(ggplot(agg, aes(g, m)) + geom_pointrange(aes(ymin = lo, ymax = hi), colour = "#0c447c") + labs(x = NULL, y = NULL))