# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("rstatix", "ggplot2"))
library(rstatix)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d$group <- factor(d$group)

# === 01 · Welch's ANOVA ===
res <- oneway.test(d[["outcome"]] ~ factor(d[["group"]]), var.equal = FALSE)
print(res)
print(rstatix::games_howell_test(data.frame(y = d[["outcome"]], g = factor(d[["group"]])), y ~ g))
gf <- factor(d[["group"]]); agg <- data.frame(g = levels(gf), m = as.numeric(tapply(d[["outcome"]], gf, mean)))
nn <- as.numeric(tapply(d[["outcome"]], gf, length)); sdv <- as.numeric(tapply(d[["outcome"]], gf, sd))
se <- sdv / sqrt(nn); tq <- qt(0.975, nn - 1); agg$lo <- agg$m - tq * se; agg$hi <- agg$m + tq * se
print(ggplot(agg, aes(g, m)) + geom_pointrange(aes(ymin = lo, ymax = hi), colour = "#0c447c") + labs(x = NULL, y = NULL))