# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("modelsummary", "car", "effectsize", "ggplot2"))
library(modelsummary)
library(car)
library(effectsize)
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d[["group"]] <- factor(d[["group"]])

# === 01 · Independent t-test ===
itt <- data.frame(score = d[["score"]], g = factor(d[["group"]]))
print(datasummary_balance(~g, data = itt, dinm = FALSE))  # Table 1 (Arel-Bundock datasummary)
res <- t.test(d[["score"]] ~ factor(d[["group"]]), var.equal = FALSE, conf.level = 0.95, alternative = "two.sided")
print(res)
print(car::leveneTest(score ~ g, data = itt, center = median))
print(effectsize::cohens_d(score ~ g, data = itt, pooled_sd = TRUE))
print(ggplot(itt, aes(g, score)) +
  geom_boxplot(fill = "#9cc2ec", colour = "#0c447c") + labs(x = NULL, y = NULL))