# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("ggplot2"))
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)

# === 01 · Principal component analysis (PCA) ===
variables <- c("x1", "x2", "x3", "x4", "x5", "x6", "x7", "x8", "x9")
d_pca <- d[, variables, drop = FALSE]
d_pca <- d_pca[complete.cases(d_pca), ]
n <- nrow(d_pca)

# ---- PCA via prcomp ----
prcomp_obj <- prcomp(d_pca, scale. = TRUE, center = TRUE)
eigenvalues <- prcomp_obj$sdev^2
pct_var <- eigenvalues / sum(eigenvalues)
cumulative <- cumsum(pct_var)

# ---- Parallel analysis for retention (kind="pca": standard correlation matrix) ----
x <- as.matrix(d_pca)
if (TRUE) x <- scale(x)
nsim <- 500L; seed <- 20260619L; kind <- "pca"
set.seed(seed)
n_pa <- nrow(x); p_pa <- ncol(x)
R_pa <- cor(x)
obs_eig <- sort(eigen(R_pa, symmetric = TRUE, only.values = TRUE)$values, decreasing = TRUE)
sim_e <- matrix(0, nsim, p_pa)
for (i in seq_len(nsim)) {
  rx <- matrix(rnorm(n_pa * p_pa), n_pa, p_pa)
  sim_e[i, ] <- sort(eigen(cor(rx), symmetric = TRUE, only.values = TRUE)$values, decreasing = TRUE)
}
sim_p95 <- apply(sim_e, 2, quantile, probs = 0.95)
k_retain <- 0L
for (i in seq_len(p_pa)) { if (obs_eig[i] > sim_p95[i]) k_retain <- k_retain + 1L else break }
k_retain <- max(1L, k_retain)
cat("Parallel analysis retain:", k_retain, "\n")

# ---- Table 1: Variance explained ----
cat("\n--- Table 1: Variance explained ---\n")
for (ci in seq_len(k_retain)) {
  cat(sprintf("  PC%d: eigenvalue=%.3f pctVar=%.1f%% cumulative=%.1f%%\n",
              ci, eigenvalues[ci], pct_var[ci]*100, cumulative[ci]*100))
}

# ---- Table 2: Correlation-scaled loadings (NO communality — PCA is data reduction) ----
# Correlation-scaled loading = eigenvector × sqrt(eigenvalue) = rotation col × sdev
load_mat <- sweep(prcomp_obj$rotation[, seq_len(k_retain), drop = FALSE], 2, prcomp_obj$sdev[seq_len(k_retain)], "*")
cat("\n--- Table 2: Component loadings (correlation-scaled) ---\n")
print(round(load_mat, 3))