# Reproducible analysis script generated by Telos
# Run from the folder holding cleaned.csv. Uncomment install.packages() the first time.
# install.packages(c("ggplot2"))
library(ggplot2)
d <- read.csv("cleaned.csv", stringsAsFactors = FALSE)
d[["participant_id"]] <- factor(d[["participant_id"]])

# === 01 · Friedman ===
conds <- c("rt_baseline", "rt_low", "rt_high")
mat <- matrix(c(d[["rt_baseline"]], d[["rt_low"]], d[["rt_high"]]), ncol = length(conds), dimnames = list(NULL, conds))
ft <- friedman.test(mat)
print(ft)
k <- ncol(mat); n <- nrow(mat); w <- unname(ft$statistic) / (n * (k - 1))
cat("Kendall's W:", w, "\n")
cat("N subjects:", n, "\n")
rbar <- colMeans(t(apply(mat, 1, rank)))
for (i in 1:(k - 1)) for (j in (i + 1):k) {
  q <- (rbar[j] - rbar[i]) / sqrt(k * (k + 1) / (6 * n))
  cat(conds[i], "-", conds[j], "p.adj =", ptukey(abs(q) * sqrt(2), k, Inf, lower.tail = FALSE), "\n") }
mm <- colMeans(mat); sdv <- apply(mat, 2, sd); se <- sdv / sqrt(nrow(mat)); tq <- qt(0.975, nrow(mat) - 1)
agg <- data.frame(cond = factor(conds, levels = conds), m = mm, lo = mm - tq * se, hi = mm + tq * se)
print(ggplot(agg, aes(cond, m, group = 1)) + geom_line(colour = "#0c447c") +
  geom_pointrange(aes(ymin = lo, ymax = hi), colour = "#0c447c") + labs(x = NULL, y = NULL))